Feature selectallcellswithtags toc
jupyterlab/jupyterlab pull request #10346
Opened 2021-06-04 16:17 UTC by NPetz

## References

closes [#8566](https://github.com/jupyterlab/jupyterlab/issues/8566)

## Code changes

- create a new method that selects all the cells that have all of the current selected tags and activates the first of those cells

## User-facing changes

- creates a new button the near the 'Clear Filters' button 

<img width="1436" alt="Screen Shot 2021-06-05 at 0 57 55" src="https://user-images.githubusercontent.com/38439788/120832338-82344b00-c59b-11eb-9944-8781f1055615.png">

## Backwards-incompatible changes

2021-06-04 17:09 UTC, goanpeca commented on packages/toc/src/generators/notebook/tagstool/index.tsx
> +          Select All Cells With Current Tags
Thanks for working on this @NPetz !

Could you please add internationalization to this ?

See for examples: https://github.com/jupyterlab/jupyterlab/blob/f0790b3ffd187b7dc923156b8ae227855abecefb/packages/toc/src/generators/notebook/toolbar_generator.tsx#L175

2021-06-04 17:09 UTC, goanpeca commented on packages/toc/src/generators/notebook/tagstool/index.tsx
> +          Select All Cells With Current Tags
Could you please add internationalization to this ?

See for examples: https://github.com/jupyterlab/jupyterlab/blob/f0790b3ffd187b7dc923156b8ae227855abecefb/packages/toc/src/generators/notebook/toolbar_generator.tsx#L175

2021-06-04 17:09 UTC, goanpeca requested changes
Thanks @NPetz 

Needs i18n 🌐  added? :)

2021-06-05 09:12 UTC, NPetz commented
Thanks for the very quick review!
I added i18n, I hope it's fine!

2021-06-05 10:46 UTC, blink1073 approved these changes
Thank you!

2021-06-06 14:32 UTC, blink1073 commented
It looks like two things are required:

Please run `jlpm run lint` to pick up the auto-formatting changes.

Please copy `toc_show_tags.png` from the UI test [output](https://github.com/jupyterlab/jupyterlab/suites/2917486147/artifacts/65490703) and replace the file in `jupyterlab/ui-tests/reference-output/screenshots` locally to pick up the visual change.

2021-06-06 14:33 UTC, blink1073 commented
@mbektas, do you mind adding an entry to our contributor guide with the above suggestion for visual changes?

2021-06-06 16:29 UTC, NPetz commented
> It looks like two things are required:
> 
> Please run `jlpm run lint` to pick up the auto-formatting changes.
> 
> Please copy `toc_show_tags.png` from the UI test [output](https://github.com/jupyterlab/jupyterlab/suites/2917486147/artifacts/65490703) and replace the file in `jupyterlab/ui-tests/reference-output/screenshots` locally to pick up the visual change.

@blink1073 

Thank you very much for your guidance!

I've run the linter and commited the changes, so that's fine.

However, I cannot find the directory you are talking about in my local files ( it seem to be listed in your .gitignore)... what's the proper course of action here?

2021-06-06 16:40 UTC, blink1073 commented
Whoops, that should have been `ui-tests` as the top level folder in your git checkout, so the same path otherwise.

2021-06-07 04:09 UTC, NPetz commented
I'm sorry, I don't know why but when I forked and cloned the repo it didn't have the `ui-tests` directory in it.
I fetched from the upstream and  changed the screenshot file so now it should be ok.

2021-06-07 06:56 UTC, NPetz commented
Well that's annoying... I guess I should have replaced `toggle-tag-2`  (and `toggle-tag-1` ?) too...
I don't understand why It didn't fail those tests the first time though....

2021-06-07 11:32 UTC, NPetz commented
So I ran the ui-tests locally and replaced all the screenshots with the new button.
Hopefully it works this time?

2021-06-07 11:34 UTC, blink1073 commented
> Hopefully it works this time?

Hopefully!  Thanks for bearing with us, UI regression testing is a new feature, we're still working out the process.  ;)

2021-06-07 11:56 UTC, blink1073 commented
UI Test is green, thanks again!  This will be ready to merge once the other tests finish.

2021-06-07 13:22 UTC, NPetz commented
> Hopefully! Thanks for bearing with us, UI regression testing is a new feature, we're still working out the process. ;)

No worries at all!
Thank you again for the support.

Hopefully I can continue contributing to the project.

2021-06-07 14:18 UTC, blink1073 commented
> Hopefully I can continue contributing to the project.

Great!

2021-06-07 14:18 UTC, merged