Added Table of contents (toc.rst) to user guide documentation
jupyterlab/jupyterlab pull request #10699
Opened 2021-07-26 14:42 UTC by AnudeepGunukula

## References

#10597 will be solved by this pr

## Code changes
I have added the toc.rst in user docs and README.md in packages/toc/  and 
.vs in .gitignore for visual studio friendliness

## User-facing changes

## Backwards-incompatible changes

2021-07-26 15:07 UTC, fcollonval requested changes
Thanks a lot @AnudeepGunukula 

Here are a few comments and suggestion.

2021-07-26 15:07 UTC, fcollonval commented on docs/source/user/toc.rst
> +Here is an animation showing the extension's use, with a notebook from the `Python Data Science Handbook <https://github.com/jakevdp/PythonDataScienceHandbook>`_ :
```suggestion
Here is an animation showing the table of content use, with a notebook from the `Python Data Science Handbook <https://github.com/jakevdp/PythonDataScienceHandbook>`_ :
```

2021-07-26 15:07 UTC, fcollonval commented on docs/source/user/toc.rst
> +containing runnable code cells, and clicking the runcell option will make the cells run in notebook.
```suggestion
containing runnable code cells, and clicking the *Run Cell(s)* option will make the cells run in notebook.
```

2021-07-26 15:07 UTC, fcollonval commented on docs/source/user/toc.rst
> +The Output is also gets numbering in the toc and the notebook, by default this ``includeOutput`` attribute is set to true.
```suggestion
The cell outputs get numbered by default in the table of contents and the notebook.
```

2021-07-26 15:07 UTC, fcollonval commented on docs/source/user/toc.rst
> +In the settings by making the attribute to false will not give numbering to outputs. Here is an animation showing its use
```suggestion
This can be tuned by changing the settings ``includeOutput`` to ``false``. Here is an animation showing its use
```

2021-07-26 15:07 UTC, fcollonval commented on docs/source/user/toc.rst
> +The collapsing of the table of contents is now having the blue bar rather than caret up/down icons as you can see from above all the demos.
I think we can remove that.

```suggestion
```

2021-07-26 15:07 UTC, fcollonval commented on docs/source/user/toc.rst
> +   jupyter labextension install @jupyterlab/toc
Non relevant

```suggestion
```

2021-07-26 15:07 UTC, fcollonval commented on docs/source/user/toc.rst
> +Once installed, extension behavior can be modified via the following settings which can be set in JupyterLab's advanced settings editor.
```suggestion
The extension behavior can be modified via settings which can be set in JupyterLab's advanced settings editor.
```

2021-07-26 15:07 UTC, fcollonval commented on docs/source/user/toc.rst
> +* **collapsibleNotebooks**: enable the ability to collapse sections of notebooks from the ToC
```suggestion
* **collapsibleNotebooks**: enable the ability to collapse sections of notebooks from the Table of Contents
```

2021-07-26 15:41 UTC, AnudeepGunukula commented
Thankyou guys for your inputs, i will make the changes and  create new gifs with light theme and suggested settings

2021-07-28 13:17 UTC, AnudeepGunukula commented
Hi, @krassowski, please once check this animation . if this fine then i will continue same settings for all remaining.
![toc](https://user-images.githubusercontent.com/55506841/127328054-38f91092-6aa9-4f69-9dda-50d870e53a27.gif)

2021-07-28 13:43 UTC, krassowski commented
It looks good to me. Optionally, you could increase the cursor size a little bit to make it nicer for users with low vision?

2021-07-29 06:01 UTC, AnudeepGunukula commented
> 
> 
> It looks good to me. Optionally, you could increase the cursor size a little bit to make it nicer for users with low vision?

yes, i will do it.

2021-07-29 06:51 UTC, fcollonval commented
One small comment on my side (and I'm to blame). We should use coherent case for _table of content_. As recommended in the documentation, lower case should be preferred. So could you check that all **T** _able of_ **C** _ontent_ are converted to _table of content_?

2021-07-29 08:01 UTC, AnudeepGunukula commented
yes, i will check it and will change all of them to lower case.

2021-07-29 16:13 UTC, AnudeepGunukula commented
Hi guys, i had made the changes you suggested to me. 
please let me know  if any new changes needed. i will fix them.

2021-07-29 17:03 UTC, krassowski reviewed
These GIFs looks so great! The text is good too; I left a few suggestions for improvements. Slightly countering @fcollonval's point, I have a preference to keep Table of Contents capitalised where referring to the field in **A**dvanced **S**ettings **E**ditor (as this is how it is displayed in the GUI) - but this is just my personal preference and I think the documentation already mixes both approaches...

The tests are failing on documentation build step with this warning:

> /home/runner/work/jupyterlab/jupyterlab/docs/source/user/toc.rst: WARNING: document isn't included in any toctree

I think you need to add the toc.rst to [docs/source/index.rst](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/index.rst) - I would suggest second half of the user documentation, somewhere near the debugger.

2021-07-30 08:19 UTC, AnudeepGunukula commented
Hi @krassowski , I had updated the index.rst and also made the suggested changes.
please let me know if any new changes needed.

2021-07-30 10:37 UTC, krassowski approved these changes
Thank you, this look great to me!

2021-07-30 10:37 UTC, krassowski commented on docs/source/user/toc.rst
> +Editor and then go to Table of Contents section and in User Preferences add ``includeOutput:false`` and save the settings, Here is an animation showing its use
```suggestion
Editor and then go to Table of Contents section and in User Preferences add ``includeOutput:false`` and save the settings. Here is an animation showing its use
```

2021-07-30 10:39 UTC, krassowski commented
One minor thing, after correcting the comma vs full stop, could you also run `jlpm run lint` so that all tests pass?

2021-08-02 03:18 UTC, AnudeepGunukula commented
Hi guys, i made all the suggested changes and also all checks were passed.
Please let me know if any changes required. I will try to fix them

2021-08-02 07:47 UTC, fcollonval approved these changes
LGTM 

Thanks for pushing this through @AnudeepGunukula

2021-08-02 07:47 UTC, merged

2021-09-10 10:08 UTC, blink1073 commented
@meeseeksdev please backport to 3.1.x