perf: scroll active toc item into view
jupyterlab/jupyterlab pull request #11413
Opened 2021-11-07 16:08 UTC by skyetim

## References

Fix #11263 .

## Code changes

Used a slightly different approach from proposed solution in the issue. When widget is called to update, it will find active cell and scroll into view if needed. 

## User-facing changes

Before:

![before](https://user-images.githubusercontent.com/5832902/136464459-4a773828-f2d2-4331-bcc1-89b80d129c2e.gif)

After: 

![after](https://user-images.githubusercontent.com/16680640/140652655-d3e1d448-95c1-4a02-9aef-869dc038ca2f.gif)

## Backwards-incompatible changes

None.

2021-11-08 08:46 UTC, fcollonval requested changes
Thanks for working on this @skyetim 

As this is related to the notebook toc, we should define a logic that is enclosed in the notebook toc generator.

To do so, you can take inspiration of https://www.carlrippon.com/scrolling-a-react-element-into-view/

The idea here is to modify the `render` function:

https://github.com/jupyterlab/jupyterlab/blob/114159269a76c4a8d4c1e725e882d7c8a7791869/packages/toc/src/generators/notebook/render.tsx#L23

And create a new element `NotebookHeading` instead of the simple `div` that will have the feature of scrolling into view; something like:

```ts
function NotebookHeading(props): JSX.Element {
  const itemRef = React.useRef<HTMLDivElement>(null);
  const { isActive } = props;
    React.useEffect(() => {    if (isActive && itemRef.current) {      itemRef.current.scrollIntoView();    }  }, [isActive]);
    return <div ref={itemRef} className={[props.className, (isActive ? 'toc-active-cell' : '')].join(' ')} >{props.children}</div>
}
```

2021-11-09 13:34 UTC, skyetim commented
Thanks for the suggestion. `scrollIntoView` will make the scroll quite weird as it will scroll the element even though it's already in view (as the following gif). I replaced it with `ElementExt.scrollIntoViewIfNeeded`. 

![scrollintoview](https://user-images.githubusercontent.com/16680640/140858100-f69c1898-f32e-4e67-9b7a-9b3eabc9153a.gif)

2021-11-10 16:11 UTC, fcollonval requested changes
Thanks for quickly applying the changes. I have a last enhancement suggestion. And it will be good to go.

2021-11-11 13:19 UTC, fcollonval approved these changes

2021-11-11 13:19 UTC, fcollonval commented
Thanks @skyetim this looks good to me

2021-11-12 07:37 UTC, merged