Only show the head of the outputs and ensure iopub outputs are correctly displayed
jupyterlab/jupyterlab pull request #11457
Opened 2021-11-14 16:59 UTC by echarles

## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/10045

## Code changes

We need to take into account the iopub messages when stripping the output to only show the defined max number of outputs.

This PR takes those messages into account. To achieve this, we also had to remove the display of the tail.

## User-facing changes

The outputs are correctly displayed when running e.g.

````
for i in range(100):
    for x in range(10):
        print(x, flush=True)
    for x in range(10):
        print(x, file=sys.stderr, flush=True)
```

the tail is not more displayed (all outputs can still be seen if the user clicks on the message `Click on this message to get the complete output.`)

## Backwards-incompatible changes

None

2021-11-16 15:29 UTC, fcollonval requested changes
Thanks @echarles I let some minor suggestions otherwise it works as expected.

2021-11-16 15:29 UTC, fcollonval commented on packages/outputarea/src/widget.ts
>                <a style="margin: 10px; text-decoration: none;">
Minor suggestion to highlight the interactive nature of the text.

```suggestion
              <a style="margin: 10px; text-decoration: none; cursor: pointer;">
```

2021-11-16 15:29 UTC, fcollonval commented on packages/outputarea/src/widget.ts
> +      //      layout.insertWidget(index, output);
We probably want to remove unused code.

```suggestion
```

2021-11-16 15:29 UTC, fcollonval commented on packages/outputarea/src/widget.ts
> +      //      i < this.trimmedOutputModels.length - this.headTailNumberOutputs;
Same here

```suggestion
```

2021-11-16 15:33 UTC, echarles commented
Thx a lot @fcollonval for the review. I have committed your suggestions.

2021-11-16 22:39 UTC, jtpio commented
This needs a quick lint pass.

2021-11-17 07:10 UTC, echarles commented
@fcollonval @jtpio The code in now linted and CI is green. This is ready for merge.

2021-11-17 07:58 UTC, fcollonval approved these changes
All green for me. Thanks @echarles

2021-11-19 06:40 UTC, echarles commented
Thx for the review and approval @fcollonval Will you merge this?

2021-11-19 07:33 UTC, fcollonval commented
> Thx for the review and approval @fcollonval Will you merge this?

Doing it now...

2021-11-19 07:33 UTC, merged

2021-11-19 07:34 UTC, fcollonval commented
@meeseeksdev please backport to 3.2.x

2021-11-20 14:34 UTC, echarles commented
Thx for the merge @fcollonval 

I have seen a need for a manual backport to 3.2.x and a branch in your repo. I have seen tags removed by @krassowski 

To avoid confusion, I have opened https://github.com/jupyterlab/jupyterlab/pull/11509 which backport this fix to 3.2.x branch.

2021-11-20 15:11 UTC, krassowski commented
I removed the tag because the backport PR was already opened by @fcollonval here: https://github.com/jupyterlab/jupyterlab/pull/11502 so your PR is a duplicate ;)

2021-11-20 15:15 UTC, echarles commented
> I removed the tag because the backport PR was already opened by @fcollonval here: #11502 so your PR is a duplicate ;)

Yeah, I was suspecting that, but for some reasons, I have not found @fcollonval PR... I will close mine. Better 2 than zero :)