Update ModelDB metadata when switching the shared model
jupyterlab/jupyterlab pull request #11493
Opened 2021-11-18 14:05 UTC by hbcarlos

Update ModelDB metadata when switching the shared model

## References
Solves #11483

## Code changes
When switching the shared model of a cell, we add the metadata to ModelDB

## User-facing changes
N/A

## Backwards-incompatible changes
N/A

2021-11-19 07:44 UTC, fcollonval requested changes
thanks @hbcarlos 

One small comment about the documentation and we are good to go

2021-11-19 07:44 UTC, fcollonval commented on packages/cells/src/model.ts
> +  public switchSharedModel(
Could you add docstring please? 

> I suggest removing `public` as we have the convention not to write it explicitly in JLab.

```suggestion
  switchSharedModel(
```

2021-11-22 09:13 UTC, fcollonval approved these changes
Thanks @hbcarlos 

> UI failure are not related

2021-11-22 09:13 UTC, fcollonval commented
@meeseeksdev please backport to 3.2.x

2021-11-22 09:24 UTC, merged

2021-11-22 10:19 UTC, hbcarlos commented
Thanks, @fcollonval!

2022-01-06 17:41 UTC, meeseeksmachine commented
This pull request has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterhub-collaboration-and-tags/11259/6