Trusted output sync
jupyterlab/jupyterlab pull request #11494
Opened 2021-11-18 14:15 UTC by trungleduc

## References
#11435 

## Code changes

WIP

## User-facing changes

When a widget display command is executed in one client, all other clients will display a prompt asking for permission to render the widget. Users can select `No`, `Yes` or `Always`, if `Always` is selected, all widgets will be rendered automatically without asking.
The dialog will be displayed only one time for each cell.

https://user-images.githubusercontent.com/4451292/142431126-1285b2fe-bd2b-4273-a3ed-650dcd7efc13.mp4

## Backwards-incompatible changes

N/A

2021-11-23 08:12 UTC, hbcarlos approved these changes
Thanks, @trungleduc! LGTM!

2021-11-23 13:37 UTC, hbcarlos commented
@jtpio Can you take a look and merge?

2021-11-24 07:52 UTC, fcollonval requested changes
I find the per output prompt far too invasive. As a user I would expect that if I trust or untrust a document, but I do see the point of trusting only some outputs.

So I would suggest getting a status only for the all notebook. This brings me to the fact that we already have a trust status on the notebook. So should we not revisit it to deal with real-time collaboration.

> I will bring this up at the next meeting.

2021-11-24 10:02 UTC, trungleduc commented
Hi @fcollonval, I initially started with only one prompt for trusting the notebook but then I realized in the context of RTC, we can trust the contents of the notebook at a moment but can not be sure about the contents coming after from other users. 

Btw I'm happy to update the PR after the conclusion of the next meeting.

2021-11-24 15:33 UTC, jtpio commented
> I will bring this up at the next meeting.

We can point folks to try it out with the Binder link on this PR since it has RTC enabled.

2021-11-25 09:36 UTC, fcollonval commented
People have nice idea in the yesterday meeting for the UI:
- [Pete] origin of Colab's iframe outputs. rather than a dialog could it render the non-interactive outputs (text/plain) for remote outputs, with a button to allow switching to the rich mime types?
- [Tony] accessibility?
- [Sylvain] a shield thing by untrusted output
- [Mike] There is already a similar pattern with trust button for the html viewer.

The idea would be to display the "plain/text" version of the output with a button (?) that allow to load the more complex view if the user trust the output. It would be good to have a way to set it up for the full notebook though - maybe extending the trust shield status bar indicator.

2021-11-25 09:39 UTC, fcollonval commented
And read the trust feature description in [notebook documentation](https://jupyter-notebook.readthedocs.io/en/stable/security.html#security-in-notebook-documents). I'm convinced that the RTC should not be considered as a special case and should follow that feature behavior.

2021-11-25 09:47 UTC, krassowski commented
> And read the trust feature description in notebook documentation. I'm convinced that the RTC should not be considered as a special case and should follow that feature behavior.

I politely disagree. We should treat it as a special case because in a sessions run by teachers/instructors for students we should not expose everyone in the class to a potential jokingly intended attack from one of the participants. Maybe this is something for which there should be roles, like only certain users have the rights to render widgets as trusted by default, and all others result in the plaintext + "I trust this output" shield button (the rationale is that the output presented interactively by the instructor/host should be trusted but the output from other participants should not; once the host trusts that output it would be trusted for everyone). Is this technically feasible to identify the host of the meeting right now, or is this something which will be only possible once the user package is in?

Also, the preview could be an isolated iframe instead of the plaintext.

2021-11-25 10:29 UTC, trungleduc commented
I agree with @krassowski on this point, but since we haven't got the RBAC yet I think it will be difficult to identify the host of a session. @hbcarlos may have more insight about it?

I like the idea about the per-output trust button but we should have also some way to trust every output. I'm thinking about this scenario:

     When I connect to a session with other clients already connected, I get a prompt for trusting all outputs.
     If I say no, I will get the "plain/text" version with a button to render it later.

2021-11-25 11:00 UTC, fcollonval commented
True I forget the sync is two ways...

For me the problem of the host is not related to the trust but as mentioned @trungleduc to sharing rights (that could already be implemented as they don't need to know about the user - they should be part of the shared session when created).

If I compare with VS Code Live Share feature (in which you can share a terminal), from the host point of view you specify the right for the sharing resources (read-only, read and write). In the case of the notebook we certainly need more rights levels (adding the execution right for instance). And we should avoid having too complex states. But it definitely seems we should reboot the RTC meeting to discuss that kind of scenarii and how to address them (for instance at first being able to support a case like _once the host trusts that output it would be trusted for everyone_ sounds to me going against what is proposed here as this is the owner of the client that says if he trusts the output or not).

2021-11-25 11:04 UTC, hbcarlos commented
> Is this technically feasible to identify the host of the meeting right now, or is this something which will be only possible once the user package is in?

I'm not 100% sure, but I don't think we can identify the host, not even with the user package in. The only way would be to have RBAC and only users with ¿`ADMIN` or `RUN`? roles can render the outputs without asking for trust.

2022-05-20 09:29 UTC, SylvainCorlay commented
I think it would be interesting to revive this (rebase the PR on top of the latest changes in RTC).

This PR reflects the current model for trust, and I don't think that we should try to revise that model as part of this PR.

2022-06-04 11:44 UTC, fcollonval requested changes
I have some questions but mostly the code looks good.

2022-06-04 11:44 UTC, fcollonval commented on packages/cells/src/model.ts
> +  get needTrustButton(): boolean {
Would you mind adding documentation for those public API?

2022-06-04 11:44 UTC, fcollonval commented on packages/cells/src/model.ts
> +            this._displayModelRequested.emit();
We probably want to emit the event after the output has been added?

2022-06-04 11:44 UTC, fcollonval commented on packages/notebook/src/truststatus.tsx
> +        context.save();
Could you confirm that this is the reason you need NotebookPanel instead of Notebook?

2022-06-07 08:11 UTC, trungleduc commented
@fcollonval Thanks for the review! Suggestions were applied in the last commit.

2022-06-07 08:50 UTC, trungleduc commented
Switched to draft since I'm having some issues with `ipywidget 8`

2022-06-07 14:01 UTC, trungleduc commented
With the changes in `ipywidgets` 8,  cell output always has the cell number on the left, so I need to move the trust button to the far right of the output area. 

https://user-images.githubusercontent.com/4451292/172399783-b8d0be55-b5f0-4e80-a3d0-a60f2ef84a24.mp4

2022-06-21 14:45 UTC, SylvainCorlay commented
This looks good to me !

2022-06-27 09:21 UTC, davidbrochart commented
Should this approach be generalized to all outputs (not only widgets), and become the [new trust mechanism](https://github.com/jupyter-server/jupyter_server/pull/891#issuecomment-1167099693)?

2022-06-27 09:38 UTC, Carreau commented
> Should this approach be generalized to all outputs (not only widgets), and become the [new trust mechanism](https://github.com/jupyter-server/jupyter_server/pull/891#issuecomment-1167099693)?

Definitely no for me, this is a completely different trust mechanism with completely different goals than the current one. This "new" trust mechanism does not consider sharing in different ways than with RT collaborations, and running headless. The current trust mechanism, is made for exchange of notebooks that will potentially be ran for example via nbconvert, or on a batch script. 

A local trust to each cell/output does not work. 

For example looking at local trust:

```
 - cd repo
 - cd cache
 - rm -rf *
 - cd .. 
 - cd .. 
```
An d assume I trust this notebook, and each cell is "trusted" independently. 
An attacker get this notebook, and reorder it, not changing the new "trust" status:

```
 - cd .. 
 - cd .. 
 - rm -rf *
 - cd repo
 - cd cache
```

And now my $HOME is gone if I run "ipython my_notebook.ipynb".  This is just an example, and when we designed the trust mechanism circa 2014, we found others examples where a set of multiple trusted and harmless items independently can become harmful together.

This is why the trust is global, and attached to the serialised version of the notebook via signature.

2022-06-27 09:47 UTC, davidbrochart commented
From @krassowski's [comment](https://github.com/jupyterlab/jupyterlab/issues/9765#issuecomment-954905151):
"I think that you misunderstood what the trust feature does. It is not there to protect from say malicious Python code. It is there to protect from consequences of automatic execution of JavaScript and SVG."

Which is in contradiction with your Python example @Carreau.

2022-10-11 00:39 UTC, ellisonbg commented
A few questions and thoughts:

* I reviewed #12756, which would make cell-trust part of the shared model. I think the translation of notebook trust in the RTC setting is "we all trust this code when any of us trust this code." If a collaborator is not trusted at that level, I don't believe they should have execute access to that shared JupyterLab to begin with. 
* I wouldn't use the notebook trust abstraction that we have to indicate if a specific human collaborator should be trusted. Anytime you allow for RTC, participants can misbehave, even without code execution. RBAC is the right tool to solve that, by giving a user the appropriate level of access based on their role. 
* I am not sure if this current PR makes sense if #12756 is merged. Would that other PR ensure that all outputs would show for all users once one of them runs (and trusts) the cell?
* I am concerned that this PR introduces a secondary trust abstraction, but doesn't tie that back to who ran the cell. If we were going to ask uses to do this type of approval ("someone ran this cell, do you want to view the output") I think we should show the identity of the person that ran the cell.

2022-10-11 07:27 UTC, trungleduc commented
@ellisonbg I'm completely in line with the direction of #12756. Closing this PR in favor of the other solution.

2022-10-11 07:27 UTC, closed without merging