Add ability to open settings editor to specific plugin's settings
jupyterlab/jupyterlab pull request #12398
Opened 2022-04-12 23:45 UTC by marthacryan

## References
Fixes #12180. 

## Code changes
Adds an extra arg to the command to open the settings editor to specify a specific plugin's settings to open. Also adds an arg to specify the label when invoked (in case the caller wants to add a label like "Open <plugin> settings". 

## User-facing changes
Note: wouldn't change any user's experience as-is, this is for extensions that might want to create a button or palette option to open their plugin's settings. 

This opens the settings editor with only the specified plugin's settings displayed in the settings panel. All plugins and the search bar are still displayed in the left side panel and if the user clicks them, the settings panel shows all plugins again and is reset to the regular editor. 

## Backwards-incompatible changes
None

2022-04-13 07:12 UTC, fcollonval requested changes
I would not implement that feature like that because it makes the UI inconsistent.

Now that #12082 is in, the command argument should set the filter on the settings and it should expand the first plugin of settings (if it exists).

It will also be good to add that feature to the JSON editor.

2022-04-26 07:05 UTC, fcollonval requested changes
Thanks @marthacryan I have two additional comments

2022-04-28 16:21 UTC, fcollonval commented on galata/test/jupyterlab/settings.test.ts
> +  expect(await page.locator('.jp-SettingsForm')).toHaveCount(1);
```suggestion
  await expect(page.locator('.jp-SettingsForm')).toHaveCount(1);
```

2022-04-28 16:23 UTC, marthacryan commented
@fcollonval Any idea what's happening with the CI failures? Looks like there's an issue with cell toolbar?

2022-04-29 06:38 UTC, fcollonval approved these changes
Thanks @marthacryan

2022-04-29 06:38 UTC, merged

2022-05-02 10:34 UTC, fcollonval commented
@meeseeksdev please backport to 3.4.x