Removes FileEditorCodeWrapper
jupyterlab/jupyterlab pull request #12439
Opened 2022-04-19 08:58 UTC by hbcarlos

## References
Follow up:
- #12338
- #12381

## Code changes
Removes the FileEditorCodeWrapper class.

## User-facing changes

## Backwards-incompatible changes

2022-04-19 10:36 UTC, fcollonval commented on packages/fileeditor/src/widget.ts
> +  private _ready = new PromiseDelegate<void>();
Let's fix the visibility (`context` has public getter so no need to have `_context` protected as it should not be set outside the constructor) and follow the naming convention (`editorWidget` -> `_editorWidget`):

```suggestion
  model: CodeEditor.IModel;
  editor: CodeEditor.IEditor;
  private _context: DocumentRegistry.Context;
  private _editorWidget: CodeEditorWrapper;
  private _mimeTypeService: IEditorMimeTypeService;
  private _ready = new PromiseDelegate<void>();
```

2022-04-19 10:37 UTC, fcollonval requested changes
Thanks @hbcarlos 

Would you mind applying the suggestion and adding a note in the [migration doc](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/extension/extension_migration.rst)

2022-04-19 11:18 UTC, hbcarlos commented
Thanks for the review @fcollonval! I applied your suggestions, let me know if it is ok.

2022-04-19 12:59 UTC, fcollonval approved these changes
Thanks @hbcarlos

2022-04-20 12:04 UTC, jtpio commented
Thanks!

2022-04-20 12:04 UTC, merged