Feat/settings editor last mode
jupyterlab/jupyterlab pull request #12466
Opened 2022-04-25 14:40 UTC by echarles

## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/12283

## Code changes

Add a setting `useJsonEditor` in the `settingeditor-extension` package. If that setting is `true, the advanced json editor is use to edit the settings.

## User-facing changes

![Untitled4](https://user-images.githubusercontent.com/226720/165112291-d7adb908-c078-4838-926f-e8d9c56135f7.gif)

## Backwards-incompatible changes

None.

2022-04-26 06:57 UTC, fcollonval requested changes
I would use an enumeration instead of a boolean as setting; something like

Default settings editor: ['UI', 'json']

2022-04-26 07:50 UTC, jtpio commented
Also, is this new option needed? Or could the menu customization via the settings be used to replace the menu entry by `"command": "settingeditor:open-json"`?

2022-04-26 08:25 UTC, echarles commented
> I would use an enumeration instead of a boolean as setting; something like Default settings editor: ['UI', 'json']

Thx @fcollonval. Yes, we can do that.

> Also, is this new option needed? Or could the menu customization via the settings be used to replace the menu entry by "command": "settingeditor:open-json"?

Thx @jtpio. With  `option`, are you meaning the new setting, or the new command? I guess you mean the latter. I have thought replacing the menu entry (which is the visual menu show here below) based on the user setting ediotr (ui or json), but I wonder if it is possible to achieve the replace without the full browser refresh. Once the menu is built, is it mutable?

<img width="328" alt="Screenshot 2022-04-26 at 10 23 48" src="https://user-images.githubusercontent.com/226720/165256242-d4508f2e-30dc-464b-a588-4d342bef2528.png">

2022-04-26 09:51 UTC, fcollonval commented
I like a lot the idea of @jtpio - but I think it is nice to still combine it with a boolean settings as menu customization is not easy for the end users.

So to layout the changes needed, you would not add a new command, but extend the `open` one to receive arguments.

If the argument defines the type of settings editor, use the argument otherwise fallback to the settings value. And I think that for 4.0 it will make sense to drop the command `'settingeditor:open-json'`. But when backporting this enhancement we should keep it around.

2022-04-28 04:40 UTC, echarles commented
> So to layout the changes needed, you would not add a new command, but extend the open one to receive arguments. If the argument defines the type of settings editor, use the argument otherwise fallback to the settings value. And I think that for 4.0 it will make sense to drop the command 'settingeditor:open-json'. But when backporting this enhancement we should keep it around.

@fcollonval I have implemented your suggestion in my latest commit. Maybe you could have a look and confirm this was the intent. If confirmed, I will then implement your suggestion `I would use an enumeration instead of a boolean as setting; something like Default settings editor: ['UI', 'json']`.

2022-04-28 04:49 UTC, echarles commented
> and I think that for 4.0 it will make sense to drop the command 'settingeditor:open-json'

I have not been able to achieve that as the execution of the `open` and `open-json` commands are defined in separated plugins.

2022-04-28 13:53 UTC, fcollonval reviewed
Thanks @echarles  yes this is the idea.

2022-04-28 13:53 UTC, fcollonval commented on packages/settingeditor-extension/src/index.ts
> +      args: { useJsonEditor: true }
```suggestion
      args: { useJsonEditor: false }
```

2022-04-28 13:53 UTC, fcollonval commented on packages/settingeditor-extension/src/index.ts
> +        (settings.get('useJsonEditor').composite as boolean)
That's the spirit

```suggestion
    execute: async ({ useJsonEditor }: { useJsonEditor?: boolean }) => {
      registry.load(plugin.id).then(settings => {
        useJsonEditor ?? (settings.get('useJsonEditor').composite as boolean)
```

2022-04-29 07:33 UTC, echarles commented
@fcollonval I have merged with latest master and resolved the conflicts.

2022-04-29 12:18 UTC, echarles commented
Galata is failing on `Open the settings editor with a specific search query `

I am not familiar with the recent setting search query. I run `openUi({ query: '' });` What should I do?

2022-05-03 06:45 UTC, echarles commented
Did a rebase on latest master and UI test is now green. A few other flows are failing mostly on splice feature but should not berelated to this PR.

2022-05-03 09:25 UTC, echarles commented
The UI regression test fails on ` Extension Manager › Search` which is not related to this PR.

@fcollonval I think this is ready to be merged.

2022-05-03 11:14 UTC, jtpio commented
> The UI regression test fails on ` Extension Manager › Search` which is not related to this PR.

Yes also noticed in other places: https://github.com/jupyterlab/jupyterlab/issues/12340#issuecomment-1115833463

2022-05-03 13:02 UTC, echarles commented
Just solved recent conflicts with master and CI is still green (exception of the not-revelant Extension Manager › Search).

2022-05-04 03:14 UTC, echarles commented
@fcollonval @jtpio I have rebased and solved the conflicts. Happy to get your reviews so we can merge and backport.

2022-05-04 09:44 UTC, fcollonval approved these changes
Thanks @echarles LGTM

> CI failure is not related

2022-05-04 10:11 UTC, merged

2022-05-04 10:11 UTC, echarles commented
@meeseeksdev please backport to 3.4.x

2022-05-04 10:12 UTC, echarles commented
Thx @fcollonval 

The backport PR is https://github.com/jupyterlab/jupyterlab/pull/12529