Make selected text translucent so the cursor is visible in vim mode
jupyterlab/jupyterlab pull request #12520
Opened 2022-05-03 20:15 UTC by Jessie-Newman

## References

#8207

## Code changes

When text is highlighted in vim mode we set a background color to it. Because the cursor appears behind the background, the cursor is entirely hidden if it is on a highlighted character. This sets the background color to be slightly transparent so the cursor is still visible. Works in both light and dark mode.

## User-facing changes
<img width="177" alt="Screen Shot 2022-05-03 at 1 39 14 PM" src="https://user-images.githubusercontent.com/2537199/166558667-4f318e2b-5732-4439-981a-76f16265ea15.png">

<img width="195" alt="Screen Shot 2022-05-03 at 1 39 01 PM" src="https://user-images.githubusercontent.com/2537199/166558676-6503cc85-e22a-4130-947d-147c1726b2f9.png">

## Backwards-incompatible changes

N/A

2022-05-03 20:23 UTC, Jessie-Newman commented
The actual correct way to fix this would be to, instead of showing the cursor as a div that moves around the page and sits behind the text, to update the background-color on the selected character. This would give us more flexibility in terms of color. Rather than using a transparent background, we could have selected text and the cursor not overlay at all. We could also specify the color of the selected character (right now for example, if the green cursor is on a green character, it's mostly unreadable).

However the cursor logic is inside of the CodeMirror package and would require changes to that directly. Additionally, changing the cursor from a div to a character background-color would be a very extensive change to their code.

So this translucent background-color solution, while less than perfect, is much smaller and requires no changes to other codebases.

2022-05-04 08:55 UTC, fcollonval requested changes

2022-05-04 08:55 UTC, fcollonval commented on packages/theme-dark-extension/style/variables.css
> +  --jp-inverse-layout-color0: 155, 155, 155; /* white */
We should not touch those generic variables as they may impact extensions styling. We should aim at something specific for the vim mode.

Looking at the DOM, when the VIM mode is activated the `cm-fat-cursor` is added to `CodeMirror cm-s-jupyter CodeMirror-wrap` in the top container.

I tried to add that CSS rule and it works as expected - feel free to tune the styling change this is more to point out a good CSS selector to fix the issue:

```css
.cm-fat-cursor .cm-overlay.cm-searching {
	opacity: 0.5;
}
```

2022-05-04 08:56 UTC, fcollonval commented
Thanks @Jessie-Newman I have a recommendation to fix this using a slightly different and more specific change.

2022-05-13 13:03 UTC, fcollonval approved these changes

2022-05-13 13:03 UTC, merged

2022-05-13 13:03 UTC, fcollonval commented
@meeseeksdev please backport to 3.4.x