Add "Open in Simple Mode" contextMenu option
jupyterlab/jupyterlab pull request #12532
Opened 2022-05-04 20:25 UTC by divyansshhh

## References
#12325 

## Code changes

Adds a new `openBrowserTabInSimpleMode` command and plugin.

## User-facing changes

This adds a "Open in Simple Mode" contextMenu option to
filebrowser-extension

## Backwards-incompatible changes

2022-05-05 07:16 UTC, fcollonval requested changes
Thanks a lot @divyansshhh 

I would propose to make the current command `filebrowser:open-browser-tab` configurable for this feature. And not display the option by default to avoid overpopulating the context menu.

Any command can be called with a JSON-serializable object. In this case we could image passing an argument `mode`. Merging your code with the existing command, the final solution will look like

```ts
    commands.addCommand(CommandIDs.openBrowserTab, {
      execute: args => {
        const widget = tracker.currentWidget;

        if (!widget) {
          return;
        }

        const mode = args["mode"] as string | undefined;

        return Promise.all(
          toArray(
            map(widget.selectedItems(), item => {
              if (mode === 'single-document') {
                const url = PageConfig.getUrl({
                  mode: 'single-document',
                  treePath: item.path
                });
                const opened = window.open();
                if (opened) {
                  opened.opener = null;
                  opened.location.href = url;
                } else {
                  throw new Error('Failed to open new browser tab.');
                }
              } else {
                return commands.execute('docmanager:open-browser-tab', {
                  path: item.path
                });
              }
            })
          )
        );
      },
      icon: addIcon.bindprops({ stylesheet: 'menuItem' }),
      label: args => args['mode'] === 'single-document' ? trans.__('Open in Simple Mode') : trans.__('Open in New Browser Tab'),
      mnemonic: 0
    });
```

To add the new entry in the context menu, users will need to set:

```json
      {
        "command": "filebrowser:open-browser-tab",
        "args": { "mode": "single-document" },
        "selector": ".jp-DirListing-item[data-isdir=\"false\"]",
        "rank": 1.6
      }
```

in _Settings_ -> _Application Context Menu_ -> `contextMenu`.

2022-05-05 07:52 UTC, divyansshhh commented
Thanks for the suggestion @fcollonval . I agree that adding `contextMenu` options for all users wouldn't scale well but is there a place where we can document that "Open in Simple Mode" is an option that is available in case someone requires it?

2022-05-05 12:36 UTC, fcollonval commented
Thanks for quickly updating the PR.

> is there a place where we can document that "Open in Simple Mode" is an option that is available in case someone requires it?

I would suggest adding a new file `ui_customization.rst` in https://github.com/jupyterlab/jupyterlab/tree/master/docs/source/user

The layout would be

```rst
.. _interface-customization:

Interface Customization
=======================

.. _context-menu-customization:

Context Menu
------------

File Browser
^^^^^^^^^^^^

<place the doc here>
```

Don't worry about filling the others sections.

> You will need to add the new file to the docs/source/user/index.md to be integrated in the documentation.

2022-05-05 12:36 UTC, fcollonval requested changes

2022-05-05 12:36 UTC, fcollonval commented on packages/filebrowser-extension/src/index.ts
> +
This is not needed any longer.

```suggestion
```

2022-05-08 12:48 UTC, divyansshhh commented on packages/filebrowser-extension/src/index.ts
> +
Yeah I missed that. Thanks

2022-05-09 13:31 UTC, fcollonval approved these changes
Thanks a lot @divyansshhh 

> CI failures are not related

2022-05-09 13:32 UTC, fcollonval commented on packages/filebrowser-extension/src/index.ts
> +
```suggestion
```

2022-05-12 07:57 UTC, merged

2022-05-12 07:57 UTC, fcollonval commented
@meeseeksdev please backport to 3.4.x

2022-05-12 07:58 UTC, jtpio commented
Thanks!

While trying this out on Binder, I noticed the advanced settings editor seems to not be displayed the default context menu entries correctly:

![image](https://user-images.githubusercontent.com/591645/168021166-f6da75e5-b71a-4a1c-beca-9216be3f231a.png)


This is not related to this change, probably tracked in a separate issue?

2022-05-12 10:21 UTC, fcollonval commented
> This is not related to this change, probably tracked in a separate issue?

Yes I have seen that for configuration that are array of objects.