Invert relationship between launcher and filebrowser
jupyterlab/jupyterlab pull request #12585
Opened 2022-05-16 06:30 UTC by fcollonval

## References

## Code changes

Make the relationship from filebrowser to launcher rather than the opposite. This is more consistent for UI without launcher.

## User-facing changes

N/A

## Backwards-incompatible changes

Drop redundant `filebrowser:create-main-launcher` command; use `launcher:create` instead.

2022-05-18 17:36 UTC, 3coins requested changes

2022-05-19 07:41 UTC, fcollonval commented
please update documentation snapshots

2022-05-23 22:43 UTC, ajbozarth approved these changes
Code LGTM, and it worked as expected when run locally

2022-05-23 23:13 UTC, 3coins approved these changes

2022-05-24 05:10 UTC, merged