Don't show alert when leaving window in collaborative mode
jupyterlab/jupyterlab pull request #12685
Opened 2022-06-10 14:47 UTC by davidbrochart

## Code changes

When in collaborative mode, it doesn't make sense to ask the user to confirm that they want to leave the page if the document is dirty in collaborative mode, because the document is auto-saved anyway from the back-end (if the server is not stopped in the next second after the last change).
However, I can see that after the page is reloaded, the document is left in a wrong state, e.g. the kernel doesn't appear to be running even though it was running previously, the cell output doesn't show the stream, etc. But this looks like an independent problem that should be fixed in another PR.

## User-facing changes

No alert box when leaving page in collaborative mode.

## Backwards-incompatible changes

None.

2022-07-20 10:11 UTC, davidbrochart commented
OK to merge?

2022-07-25 09:24 UTC, fcollonval requested changes
It seems a bit too broad - if the dirty state is not the consequence of a collaborative document, this sounds dangerous.

As discuss at the JupyterLab meeting, the save button will likely stay even with auto-save to allow the user to trigger the file dump. So I am not convinced we should drop the alert.

2022-07-25 09:33 UTC, davidbrochart commented
I think we could auto-save also when all clients disconnect, not just after a document change. This way, there would still be no need for the user to press the save button. We could also auto-save all documents at server exit.
What do you think?

2022-10-11 01:32 UTC, ellisonbg commented
Wouldn't we want to keep the dialog to cover cases when the frontend changes are not fully sync'd with the backend?

2023-03-13 08:52 UTC, fcollonval commented
Closing as UI RTC integration has been factored out of core JupyterLab.

2023-03-13 08:52 UTC, closed without merging