Fix memory leaks
jupyterlab/jupyterlab pull request #12750
Opened 2022-06-29 13:30 UTC by fcollonval

## References

Follow-up of https://github.com/jupyterlab/benchmarks/pull/100 that introduces memory leaks analysis

## Code changes

- Remove widget.id from various mapping
- Disconnect correctly signals following notebook switch in cell tags
- Dispose the sharedModel when switching it
- Dispose modelDB when a model is disposed
- Release disposable items in open with menu in context menu
- Clear settings connection in execution indicator

## User-facing changes

None

## Backwards-incompatible changes

N/A

2022-06-30 19:01 UTC, krassowski requested changes

2022-07-04 07:50 UTC, fcollonval commented on packages/debugger/src/handler.ts
> +      removeHandlers();
Thanks for the review @krassowski I solved it by stopping the debugger if it is active when the widget is disposed.

2022-07-04 23:54 UTC, krassowski approved these changes

2022-07-06 06:18 UTC, merged

2022-07-06 06:18 UTC, fcollonval commented
@meeseeksdev please backport to 3.4.x