Add an option to enable "fast checks" of the jupyter lab build.
jupyterlab/jupyterlab pull request #12844
Opened 2022-07-22 16:45 UTC by thetorpedodog

This adds the `fast_build_check` option to the `AppOptions`
configuration. A user can set this option to `true` to avoid performing
expensive work like downloading data from NPM and computing hashes when
the install is in a known-good state or the user cannot actually trigger
a rebuild.

## References

Fixes #12797.

## Code changes

[see change description above]

## User-facing changes

No user-facing changes.

## Backwards-incompatible changes

No backwards-incompatible changes.

2022-07-25 08:04 UTC, fcollonval requested changes
Thanks @thetorpedodog I would go for a wording like `skip_build_check` that highlights a risk of turning it on.

Otherwise this is looking good to me.

2022-07-25 17:58 UTC, thetorpedodog commented
> I would go for a wording like `skip_build_check` that highlights a risk of turning it on.

I went with `skip_full_build_check` to reflect that there still is *a* build check going on, but not a complete check. If you think `skip_build_check` is a better name, I will gladly change it, though.

Thanks for the review!

2022-08-01 19:47 UTC, thetorpedodog commented
@fcollonval a gentle bump in case this fell off your radar

2022-08-05 09:20 UTC, fcollonval approved these changes
Thanks for the bump and the follow-up @thetorpedodog

2022-08-05 09:20 UTC, merged

2022-08-05 09:20 UTC, fcollonval commented
@meeseeksdev please backport to 3.4.x

2022-09-15 06:41 UTC, jhgoebbert commented
This reads like a great feature. But how is it supposed to be turned on 🤔   

Looking at the code it reads for me as if it is not yet exposed to some entry points like `jupyter lab`.  
It seems to be non-accessible same as this option: https://github.com/jupyterlab/jupyterlab/issues/8604#issuecomment-648287294