Added token for modes and themes registries
jupyterlab/jupyterlab pull request #12861
Opened 2022-07-26 13:24 UTC by JohanMabille

This fixes some issues reported in #12812:

- matchBtackets
- smartIndent
- codeFolding
- foldGutter

This also adds a token for modes and themes registry.

2022-07-27 09:03 UTC, fcollonval requested changes
Using tokens is nice. But this requires changing a bit the current structure to not use static object. In particular the `editorThemeRegistry`. They should be propagated to the `EditorConfiguration`. Or the logic should be similar to the `EditorModeRegistry` that modifies a static list.

Otherwise, providing a different theme registry overriding the token will not have the expected outcome.

If we want to align more with other APIs, the generic pattern are:

- tokens that define registries
- registries provide factories
- factories instantiate objects

But that would require more work for the code editor.

2022-07-28 10:27 UTC, JohanMabille commented
@fcollonval I removed the token API for now, so we don't have backward incompatible changes when we add it later.

> Or the logic should be similar to the EditorModeRegistry that modifies a static list.

Not sure to understand why this would work. The `EditorConfiguration` works with function that modifies the static list, so even if another extension defines another EditorModeRegistry, this later won't be used by the `EditorConfiguration` object and we'll run into the same issue as with the previous definition ot editorThemeRegistry.

My understanding is that we would also need to propagate the mode registry object to the editor configuration object to get the expected behavior. But that can be done after 4.0.

2022-08-02 08:28 UTC, jtpio commented on packages/codemirror/src/editortheme.ts
> +export namespace Theme {
It would be nice to add some basic docstrings here for consistency.

2022-08-02 12:56 UTC, fcollonval commented
I'm taking over this PR.

I added a test for adding a mode (not yet pushed)
I was testing adding a theme but actually the reconfiguration of the editors are not happening. So I'm working to fix that.

2022-08-04 13:03 UTC, fcollonval commented
bot please update snapshots

2022-08-05 09:09 UTC, fcollonval commented
bot please update snapshots

2022-08-05 10:30 UTC, fcollonval commented
bot please update snapshots

2022-08-05 12:53 UTC, fcollonval commented
bot please update galata snapshots

2022-08-05 14:08 UTC, fcollonval commented
Kicking the CI

2022-08-05 15:50 UTC, fcollonval approved these changes

2022-08-05 15:50 UTC, merged