Fix resizing of debugger variable explorer grid
jupyterlab/jupyterlab pull request #12943
Opened 2022-08-13 08:24 UTC by firai

## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/12942.

## Code changes

Remove custom `onMouseDown` handler in the debugger variable explorer grid to let the default `@lumino/datagrid` `onMouseDown` handle resize requests.

## User-facing changes

## Backwards-incompatible changes

None

2022-08-13 14:14 UTC, firai commented
Seems like the link test is failing because the link on this line is unreachable, unrelated to this PR:
https://github.com/jupyterlab/jupyterlab/blame/master/docs/source/extension/internationalization.rst#L58
It's a bit unusual, but the whole LaBRI domain seems to have been unreachable for several days now. Not sure if it's going to persist and whether a replacement intro article to `gettext` should be sought.

Not sure what happened with the `js-testutils` test. Seems to be a network issue, and maybe the test just needs to be restarted?

2022-08-13 18:55 UTC, krassowski requested changes
Thank you for diagnosing the problem and a quick fix! Looking at the code path, the selection update that happens `onMouseDown` is still needed. Here is why: the `selected` signal updates the `selectedVariable` state of the model:

https://github.com/jupyterlab/jupyterlab/blob/451a00265893eb70ed723e18e22321f2161ec444/packages/debugger/src/panels/variables/grid.ts#L143-L151

And subsequently, this is used when the user issues a command to `Inspect variable`:

https://github.com/jupyterlab/jupyterlab/blob/8fb10e4855da0ba30eac7d978f2fb88a9613f77b/packages/debugger-extension/src/index.ts#L340-L359

While the variable to inspect might be passed directly to the command, there are times when it will not be the case, for example when invoked from command palette or via shortcut; these paths might be the only way to access some functions for users of assistive technologies.

I think that instead of removing the event handler, we need to propagate the event back to the lumino's `BasicMouseHandler` (via `super.onMouseDown(event)`).

2022-08-14 02:05 UTC, firai commented
Thanks for the review. I can keep the current emitter and invoke `super.onMouseDown(event)` as suggested. I suppose there isn’t a way to avoid hit testing twice.

In the longer term, should the signal emission be moved upstream instead? I'm not familiar with how TS inheritance works, but I would imagine that it's possible to have `BasicMouseHandler` functions emit the signal and just overload the signal handler? I assume that this isn’t the only application of `datagrid` with assistive needs. For example, I understand that the `csvviewer` extension just uses the `BasicMouseHandler`, so it seems like it may not be able to feed the selected data to assistive services based on your description.

2022-08-14 12:10 UTC, krassowski commented
> In the longer term, should the signal emission be moved upstream instead? [...]  I assume that this isn’t the only application of datagrid with assistive needs

Yes, you are right.

> For example, I understand that the csvviewer extension just uses the BasicMouseHandler, so it seems like it may not be able to feed the selected data to assistive services based on your description?

Yes. The `datagrid` does not have perfect accessibility support yet, but we can make breaking changes in needed in lumino v2 ([soon](https://github.com/jupyterlab/lumino/issues/341)). 

> I understand that the `csvviewer` extension just uses the BasicMouseHandler, so it seems like it may not be able to feed the selected data to assistive services based on your description?

In fact it handles accessibility needs better because it does not try to re-implement selection handling as the debugger does.

The solution that I propose for debugger indeed only helps users who can still use the mouse pointer - `selectedVariable` does not gets updated/triggered with keyboard navigation in the debugger table (we just use `BasicKeyHandler`). So I agree that customization of of `BasicMouseHandler.onMouseDown` should ultimately go away.

Instead, we would need to re-wire the `selectedVariable` to be updated when [`SelectionModel.changed`](https://github.com/jupyterlab/lumino/blob/578509cae6af5567975a6ed2e6bc9d8a1927a078/packages/datagrid/src/selectionmodel.ts#L99-L104) fires up (in our context `BasicSelectionModel.changed`) and delegate handling of mouse and keyboard to lumino's data grid. This would help because the `changed` fires for both mouse *and* keyboard events.

2022-08-14 12:30 UTC, krassowski commented
> Instead, we would need to re-wire the `selectedVariable` to be updated when [`SelectionModel.changed`](https://github.com/jupyterlab/lumino/blob/578509cae6af5567975a6ed2e6bc9d8a1927a078/packages/datagrid/src/selectionmodel.ts#L99-L104) fires up (in our context `BasicSelectionModel.changed`) and delegate handling of mouse and keyboard to lumino's data grid. This would help because the `changed` fires for both mouse _and_ keyboard events.

Just to clarify, I am not requesting pursing such solution in this PR (but if you attempt it I am happy to review)  :)

2022-08-15 15:33 UTC, firai commented
I won't attempt the more elaborate rewire in this PR unless I have to. Since there's a simple fix available and since the impact of the bug/regression is significant (at least for me as a user), I propose that we implement the simple fix for now so that it can also be backported. It seems like the more complete refactor could benefit from additional discussions and coordination with the Lumino project anyway.

2022-08-16 04:57 UTC, firai commented
Just so the refactoring that you proposed doesn't get lost in the mix, I have added a new issue at #12946. Feel free to edit or let me know if I've mischaracterized anything.

2022-08-16 12:09 UTC, fcollonval approved these changes
Thanks @firai

2022-08-16 12:10 UTC, merged

2022-08-16 12:10 UTC, fcollonval commented
@meeseeksdev please backport to 3.4.x