Fix illegible white on yellow text of stacktrace in dark theme
jupyterlab/jupyterlab pull request #13249
Opened 2022-10-15 02:10 UTC by NikolayXHD

## References

Fixes #13248

## User-facing changes

![image](https://user-images.githubusercontent.com/12046452/195964034-24dec1f9-395c-415a-a633-303a19715981.png)

2022-10-15 13:46 UTC, krassowski commented
Thanks for looking into this.  While this fixes the problem of white text on yellow background:
- the proposed selector will match outputs other than stacktrace and distort the expected behaviour (of yellow markers producing yellow background),
    - instead we could target the traceback with `jp-RenderedText[data-mime-type="application/vnd.jupyter.stderr"]` selector
- it introduces a problem of red text on red background (see screenshot below)
   - instead we could keep the yellow as yellow, but make the text black if in yellow highlight in dark mode; the problem is that our selector would then have a precedence over foreground colour classes erasing their effect
     - therefore we need to use `:where` selector to reduce the specificity to zero

![Screenshot from 2022-10-15 14-26-13](https://user-images.githubusercontent.com/5832902/195988960-6a7fcc26-9c3a-40c9-90af-f004da5a8d70.png)

So, a plausible solution would be:

```css
:where(.jp-RenderedText[data-mime-type="application/vnd.jupyter.stderr"] pre .ansi-yellow-bg) {
  color: black;
}
```

which would produce:

![Screenshot from 2022-10-15 14-45-22](https://user-images.githubusercontent.com/5832902/195989788-75c6ede0-cd3f-4b99-8504-bd2ff15ca281.png)


This seems better to me. Yet, I am not fully convinced on that one either; an alternative would be to swap the yellow markers for another colour when parsing the stacktrace.

Test code:

<details>
```python
class Test:
    def __init__(self, *args, **kwargs):
        raise Exception()

Test(
    a=11111,
    b="can you read me?",
    c=True is False,
    d=[i for i in range(1)],
    e={**{}},
    f=Exception
)
````

</details>

2022-10-15 13:47 UTC, krassowski requested changes
As per comment above.

2022-10-15 13:47 UTC, krassowski commented on packages/theme-dark-extension/style/theme.css
> +}
```suggestion
:where(.jp-RenderedText[data-mime-type='application/vnd.jupyter.stderr'] pre .ansi-yellow-bg) {
  color: black;
}
```

2022-10-15 14:51 UTC, NikolayXHD commented
Agree, white -> black foreground solution looks much better overall. Also thank you for figuring out the issue of specificity.

2022-10-17 13:34 UTC, fcollonval approved these changes
Thanks @NikolayXHD

2022-10-26 09:20 UTC, fcollonval commented
CI failures are not related

2022-10-26 09:20 UTC, merged