Link the background colors and the ui font colors in the relevant css.
jupyterlab/jupyterlab pull request #13276
Opened 2022-10-19 16:36 UTC by HaudinFlorence

## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/13152
This PR replaces #13173
## Code changes

Colors in the interface may change slightly.

## User-facing changes

## Backwards-incompatible changes

2022-10-19 17:21 UTC, HaudinFlorence commented
bot please update snapshots

2022-10-28 09:50 UTC, fcollonval commented
bot please update snapshots

2022-10-28 12:16 UTC, HaudinFlorence commented
bot please update snapshots

2022-11-07 11:08 UTC, HaudinFlorence commented
bot please update snapshots

2022-11-10 16:16 UTC, HaudinFlorence commented
bot please update snapshots

2022-11-21 16:21 UTC, HaudinFlorence commented
The PR has just been rebased with master and should be ready for review.

2022-11-22 10:38 UTC, fcollonval commented
bot please update snapshots

2022-11-22 15:18 UTC, jtpio commented
Looking at the snapshot diff some changes don't look desired?

![image](https://user-images.githubusercontent.com/591645/203351492-d7a05f98-6669-4328-b499-cc01ea358ca1.png)

2022-11-23 14:51 UTC, HaudinFlorence commented
bot please update snapshots

2022-11-23 14:55 UTC, HaudinFlorence commented
> Looking at the snapshot diff some changes might not be desired?
> 
> ![image](https://user-images.githubusercontent.com/591645/203351492-d7a05f98-6669-4328-b499-cc01ea358ca1.png)

Problematic changes that were reducing the contrast may have been reverted in commit 
dca202b

2022-11-24 15:33 UTC, HaudinFlorence commented
bot please update snapshots

2022-11-24 16:16 UTC, HaudinFlorence commented
The PR has been rebased. As a remark comparing the snapshots, it seems that the notebook icons don't seeam to have the right orange color (maybe a reminiscence of PR #13468). Not sure also that the switch label has been reset to its previous initial color.

2022-11-28 08:26 UTC, fcollonval requested changes
Thanks @HaudinFlorence could you please remove some of the dead code.

About the notebook icon color, indeed #13279 introduced some regression. Could you correct them in a separate PR.

What I saw:
- Light theme:
  - The notebook icon and the switch true position should be md-orange-900 not md-orange-700
- Dark theme:
  - Jupyter, notebook, json and console icons are not proper. There is a shift to lighter color for the brand and the warning scales. So could you also correct that please.
- We forget to add fallback value for the switch color CSS properties `--jp-switch-color`, `--jp-switch-true-position-color`

2022-11-28 08:26 UTC, fcollonval commented on packages/rendermime/style/base.css
> +  /*color: var(--jp-ui-font-color0);*/
Dead code

```suggestion
```

2022-11-28 08:26 UTC, fcollonval commented on packages/settingeditor/style/base.css
> +  /*color: var(--jp-content-font-color1);*/
Dead code

```suggestion
```

2022-11-28 08:31 UTC, HaudinFlorence commented
> Thanks @HaudinFlorence could you please remove some of the dead code.
> 
> About the notebook icon color, indeed #13279 introduced some regression. Could you correct them in a separate PR.
> 
> What I saw:
> 
> * Light theme:
>   
>   * The notebook icon and the switch true position should be md-orange-900 not md-orange-700
> * Dark theme:
>   
>   * Jupyter, notebook, json and console icons are not proper. There is a shift to lighter color for the brand and the warning scales. So could you also correct that please.
> * We forget to add fallback value for the switch color CSS properties `--jp-switch-color`, `--jp-switch-true-position-color`

Ok. I will try to correct this in a separate PR

2022-11-28 10:00 UTC, fcollonval approved these changes

2022-11-28 11:28 UTC, HaudinFlorence commented
> > Thanks @HaudinFlorence could you please remove some of the dead code.
> > About the notebook icon color, indeed #13279 introduced some regression. Could you correct them in a separate PR.
> > What I saw:
> > 
> > * Light theme:
> >   
> >   * The notebook icon and the switch true position should be md-orange-900 not md-orange-700
> > * Dark theme:
> >   
> >   * Jupyter, notebook, json and console icons are not proper. There is a shift to lighter color for the brand and the warning scales. So could you also correct that please.
> > * We forget to add fallback value for the switch color CSS properties `--jp-switch-color`, `--jp-switch-true-position-color`
> 
> Ok. I will try to correct this in a separate PR

This is done in PR #13500

2022-12-05 09:18 UTC, HaudinFlorence commented
Are there other changes that may be useful on this PR ?

2022-12-05 16:26 UTC, merged