Set font sizes with css variables
jupyterlab/jupyterlab pull request #13305
Opened 2022-10-25 15:32 UTC by HaudinFlorence

Set some font sizes with css variables. The idea behind this PR is to reduce the use of fixed defined font sizes, in a perspective of building a theme editor when the user can chose a base font size from which other font sizes are calculated through scale factors.

## References

## Code changes

## User-facing changes

## Backwards-incompatible changes

2022-10-28 09:49 UTC, fcollonval commented on packages/launcher/style/base.css
> +  line-height: var(--jp-ui-font-size1); /*initially was 14px*/
I would change the `line-height` to be proportional with the `font-size` to keep the default ratio. See https://developer.mozilla.org/en-US/docs/Web/CSS/line-height

2022-12-14 10:24 UTC, fcollonval requested changes
@HaudinFlorence would you mind rebasing this PR? and modifying the size so that there is not visual regression (or at least not as large as currently):

![image](https://user-images.githubusercontent.com/8435071/207570228-d831f7b7-ad18-4c7d-8196-3aff6e28d9ad.png)

For now the PR is increasing the size of the cards.

2022-12-16 07:56 UTC, fcollonval requested changes
Almost there.

I guess the height or the line height is not proper because the card label is shifted down so much that the second line for the kernel name is half cut. Could you fix that please?

![image](https://user-images.githubusercontent.com/8435071/208050770-a5c694b5-8c04-4a07-8578-d5a5667fb315.png)

2022-12-16 15:15 UTC, fcollonval commented
Thanks the last commit makes the change imperceptible.

bot please update snapshots

2022-12-16 15:25 UTC, HaudinFlorence commented
bot please update galata snapshots

2022-12-19 15:16 UTC, fcollonval approved these changes

2022-12-19 15:16 UTC, merged