Set fallback values for icons colors.
jupyterlab/jupyterlab pull request #13468
Opened 2022-11-22 14:56 UTC by HaudinFlorence

## References

This PR is a follow up of PR https://github.com/jupyterlab/jupyterlab/pull/13279 and should fix issue https://github.com/jupyter/notebook/issues/6633 reporting that icons are not visible with the jupyterlab-night theme

## Code changes

In packages/ui-components/style/icons.css, add fallback values for the css variables related to the colors of the icons in the launcher.
## User-facing changes

## Backwards-incompatible changes

2022-11-22 15:03 UTC, fcollonval requested changes
Two syntax typos

otherwise it looks good. Thanks @HaudinFlorence 

> Could you please provide a screenshot using https://github.com/martinRenou/jupyterlab-night to confirm it fixes the issue?
> Once the theme is installed you can run `jupyter lab --dev-mode --extensions-in-dev-mode` to be able to select the external theme.

2022-11-22 15:10 UTC, jtpio commented
> Once the theme is installed you can run `jupyter lab --dev-mode --extensions-in-dev-mode` to be able to select the external theme.

It's also possible to test this on the dev Binder: https://mybinder.org/v2/gh/HaudinFlorence/jupyterlab/add_fallback_values_for_icons_colors?urlpath=lab

And installing `jupyterlab-night` in a terminal with `pip install jupyterlab-night`, then reloading the page.

2022-11-22 17:54 UTC, HaudinFlorence commented
> Two syntax typos
> 
> otherwise it looks good. Thanks @HaudinFlorence
> 
> > Could you please provide a screenshot using https://github.com/martinRenou/jupyterlab-night to confirm it fixes the issue?
> > Once the theme is installed you can run `jupyter lab --dev-mode --extensions-in-dev-mode` to be able to select the external theme.

Unfortunately, the PR doesn't fix the issue of the icons not displaying in jupyterlab-night theme.

2022-11-22 18:03 UTC, HaudinFlorence commented
bot please update snapshots

2022-11-22 20:31 UTC, krassowski commented
One thing that we did not consider in #13279 is updating the documentation. Specifically there is a list of available icon classes which may be worth updating: https://jupyterlab.readthedocs.io/en/latest/extension/ui_components.html#available-icon-classes. Would it be worth doing so in this PR or a follow up?

2022-11-22 20:34 UTC, jtpio commented
Kicking CI as only 2 checks were triggered on the last changes:

![image](https://user-images.githubusercontent.com/591645/203415691-0b343051-a8e6-4ca6-8a1c-17b6d943a8da.png)

2022-11-23 07:14 UTC, jtpio commented on packages/ui-components/style/icons.css
> +  fill: var(--jp-text-editor-icon-color), var(--jp-inverse-layout3));
Looks like the number of parenthesis is unbalanced:

```suggestion
  fill: var(--jp-text-editor-icon-color, var(--jp-inverse-layout3));
```

2022-11-23 07:14 UTC, jtpio commented on packages/ui-components/style/icons.css
> +  fill: var(--jp-inspector-icon-color), var(--jp-inverse-layout3));
Same as above:

```suggestion
  fill: var(--jp-inspector-icon-color, var(--jp-inverse-layout3));
```

2022-11-24 10:45 UTC, fcollonval approved these changes
Thanks @HaudinFlorence

2022-11-24 16:02 UTC, jtpio commented
I restarted the failed `examples` now that a new `jupyter_server` has been released with https://github.com/jupyter-server/jupyter_server/pull/1088.

It's still failing but with a different error now, which does not look related to this change (it's also failing on https://github.com/jupyterlab/jupyterlab/pull/13476): https://github.com/jupyterlab/jupyterlab/actions/runs/3530210941/jobs/5946555817

2022-11-24 16:25 UTC, HaudinFlorence commented
It seems that the memory leak test are failing

2022-11-24 18:27 UTC, fcollonval commented
> It seems that the memory leak test are failing

This is not related to this PR. It is the case since a while.

2022-11-25 08:28 UTC, merged

2022-11-25 08:28 UTC, fcollonval commented
@meeseeksdev please backport to 3.6.x

2022-11-25 13:39 UTC, jtpio commented
Thanks @HaudinFlorence and @fcollonval!