Removes nested A tag from extensionmanager code
jupyterlab/jupyterlab pull request #13845
Opened 2023-01-23 21:46 UTC by JasonWeill

## References

Fixes #13664.

## Code changes

Removes redundant `a` tag that had been moved to its current location in a change by @fcollonval :

https://github.com/jupyterlab/jupyterlab/blob/c6d57dc28dd566aa60fe95a7548640143fb443ee/packages/extensionmanager/src/widget.tsx#LL240C36-L240C42

(Note that the tag already existed in the code; in #12866, it was merely moved)

Browsers could handle this link; the nested `a` tag was causing errors in the Firefox console, but no apparent loss of functionality.

## User-facing changes

None.

## Backwards-incompatible changes

None.

2023-01-24 17:19 UTC, fcollonval requested changes
Thanks @JasonWeill 

It looks this is polluted by changed related to xterm.js upgrade. Would you mind removing that from this PR?

2023-01-24 17:33 UTC, JasonWeill commented
@fcollonval Removed stray changes from #13685.

2023-01-25 07:54 UTC, fcollonval commented on packages/extensionmanager/src/widget.tsx
> +            breakLabel='...'
```suggestion
            breakLabel="..."
```

2023-01-25 16:11 UTC, fcollonval approved these changes
Thanks

> CI failure are not related

2023-01-25 16:11 UTC, merged