Mention how to fix pixman, cairo missing library errors that occur while running tests in readthedocs
jupyterlab/jupyterlab pull request #13956
Opened 2023-02-09 18:37 UTC by andrii-i

## References

Local test runs sometimes fail due to missing `pixman` and/or `cairo` (for Mac computers with Apple silicon) missing packages required by `canvas`. This commit fixes formatting of the command that fixes this problem in "Installing JupyterLab" subsection of "Contribute" section of readthedocs, adds description of the error and how to fix it to "Build and Run the Tests" subsection of the same doc. 

- Fixes #13938 

## Code changes

None, only documentation changes

## User-facing changes

"Contribute" section of readthedocs

## Backwards-incompatible changes

None

2023-02-09 19:38 UTC, JasonWeill commented on docs/source/developer/contributing.rst
> +If you see a test run fail with ``Library not loaded: '@rpath/libpixman-1.0.dylib'`` (or different library, for example ``libcairo.2.dylib`` for Mac computers with Apple silicon) while running the
```suggestion
If you see a test run fail with ``Library not loaded: '@rpath/libpixman-1.0.dylib'``
(or a different library, such as ``libcairo.2.dylib`` for Mac computers with Apple
Silicon chips) while running the
```

2023-02-09 23:53 UTC, JasonWeill approved these changes

2023-02-10 08:57 UTC, fcollonval requested changes
Thanks @andrii-i 

Could we change the documentation to mention at a single place the require work around to ease the maintenance and accuracy of the documentation?

For instance I would use the section `Installing Node.js` at line 263 as single source of truth (as it is a requirement to install JupyterLab and appear first when people are reading the doc) with two sections: _with conda_ and _with homebrew_. Then in the other places you could use a reference to that section.

Additionally, don't make one note stands out compare to the others. There is no reason to highlight it for all users.

2023-02-10 20:17 UTC, andrii-i commented
@fcollonval thank you for review and feedback. Implemented comments by moving solution instructions to 'Installing Node.js' section and referring to it in other places. Also rolled back one note standing out

2023-02-13 08:35 UTC, fcollonval reviewed
Thanks @andrii-i for taking into account the review.

2023-02-13 08:35 UTC, fcollonval commented on docs/source/developer/contributing.rst
> +est`` workflows apply.
Small format issue - this line break is introducing a space in the final doc.

```suggestion
We use ``jest`` for all tests, so standard ``jest`` workflows apply.
```

2023-02-13 08:35 UTC, fcollonval approved these changes

2023-02-13 08:35 UTC, merged

2023-02-13 17:32 UTC, andrii-i commented
Thanks @fcollonval