Property inspector styling fixes
jupyterlab/jupyterlab pull request #14069
Opened 2023-02-23 01:23 UTC by JasonWeill

## References

Fixes #13987.

## Code changes

Modifies the property inspector (notebook tools) to use similar styling to the Running Terminals and Kernels UI.

## User-facing changes

The Property Inspector used larger text, in normal weight, with Title Case for headings:

![image](https://user-images.githubusercontent.com/93281816/218590747-e588c3d2-6c80-42a6-8020-02fbd7a218a6.png)

When expanded, the "Common Tools" section had no space between the bottommost control and a boundary line:

![image](https://user-images.githubusercontent.com/93281816/218591072-1e249de6-976a-4c54-91c6-0b492cdd99bb.png)

After changing this, the headers use small text in bold:

![image](https://user-images.githubusercontent.com/93281816/220801202-71d9c81d-5f87-45fb-86c6-6947a7114a0e.png)

And, when expanded, no stray line appears at the bottom:

![image](https://user-images.githubusercontent.com/93281816/220801245-e417a2ce-26c0-40c9-8727-74f05cef3942.png)

## Backwards-incompatible changes

None.

2023-02-23 02:18 UTC, andrii-i commented on packages/ui-components/src/components/collapser.ts
> +const collapsedClass = 'jp-Collapse-header-collapsed';
Should we use all caps for consts to be consistent with other places. For example:
https://github.com/jupyterlab/jupyterlab/blob/3ecf75ac8eda5f11e55f318658577bba227ecdf6/packages/cells/src/collapser.tsx#L16

```suggestion
const COLLAPSED_CLASS = 'jp-Collapse-header-collapsed';
```

2023-02-23 02:19 UTC, andrii-i commented on packages/ui-components/src/components/collapser.ts
>      this.addClass('jp-Collapse');
Should we change this to use all caps global const instead? See https://github.com/jupyterlab/jupyterlab/pull/14069/files#r1115181206

2023-02-23 02:24 UTC, andrii-i reviewed
Fixes the problem, line at the bottom of common tools section in property inspector now has spacing vs next section. Please see some suggestions on displaying consts.

2023-02-23 02:24 UTC, andrii-i commented on packages/ui-components/src/components/collapser.ts
>      this._header.addClass('jp-Collapse-header');
Should we change this to use all caps global const instead? See https://github.com/jupyterlab/jupyterlab/pull/14069/files#r1115181206

2023-02-23 02:24 UTC, andrii-i commented on packages/ui-components/src/components/collapser.ts
> +      className: 'jp-Collapser-icon'
Should we change this to use all caps global const instead? See https://github.com/jupyterlab/jupyterlab/pull/14069/files#r1115181206

2023-02-23 02:24 UTC, andrii-i commented on packages/ui-components/src/components/collapser.ts
> +    titleSpan.classList.add('jp-Collapser-title');
Should we change this to use all caps global const instead? See https://github.com/jupyterlab/jupyterlab/pull/14069/files#r1115181206

2023-02-23 02:24 UTC, andrii-i commented on packages/ui-components/src/components/collapser.ts
>      this._content.addClass('jp-Collapse-contents');
Should we change this to use all caps global const instead? See https://github.com/jupyterlab/jupyterlab/pull/14069/files#r1115181206

2023-02-23 02:24 UTC, andrii-i commented on packages/ui-components/src/components/collapser.ts
>      this.addClass('jp-Collapse');
Should we change this to use all caps global const instead? See https://github.com/jupyterlab/jupyterlab/pull/14069/files#r1115181206

2023-02-23 02:24 UTC, andrii-i commented on packages/ui-components/src/components/collapser.ts
>      this._header.addClass('jp-Collapse-header');
Should we change this to use all caps global const instead? See https://github.com/jupyterlab/jupyterlab/pull/14069/files#r1115181206

2023-02-23 23:34 UTC, krassowski commented
bot please update galata snapshots

2023-02-23 23:35 UTC, krassowski commented
bot please update documentation snapshots

2023-02-24 00:16 UTC, andrii-i approved these changes

2023-02-24 00:51 UTC, krassowski commented
Kicking CI

2023-02-24 15:05 UTC, fcollonval requested changes
Thanks @JasonWeill 

It seems the new structure broke the integrationt tests for the metadataform feature and a snapshot was wrongly updated: galata/test/documentation/debugger.test.ts-snapshots/debugger-activate-documentation-linux.png

2023-02-24 19:46 UTC, JasonWeill commented
bot please update galata snapshots

2023-02-24 20:44 UTC, JasonWeill commented
please update galata snapshots

2023-03-01 22:53 UTC, JasonWeill commented
bot please update documentation snapshots

2023-03-01 23:04 UTC, JasonWeill commented
@krassowski @fcollonval I'd like to update the UI test screen shots to reflect the new visual style; I reviewed the test reports, and the revised screen shots are correct. I've been asking the bot to update screen shots, but nothing seems to be getting updated. Is there something else that I can do to move this PR forward? Thanks!

2023-03-01 23:06 UTC, krassowski commented
Can you try first merging the master branch in? Is there anything specific in the action logs?

2023-03-01 23:07 UTC, krassowski commented
This one sorts to be still running: https://github.com/jupyterlab/jupyterlab/actions/runs/4308717001

2023-03-02 21:44 UTC, JasonWeill commented
bot please update documentation snapshots

2023-03-02 22:42 UTC, JasonWeill commented
@fcollonval After rebasing this branch and regenerating snapshots successfully, CI is now green on this PR ✅

2023-03-03 09:07 UTC, krassowski commented
@JasonWeill the CI suite has not run fully yet because bot does not have permissions to trigger them. Kicking CI to run them now.

2023-03-03 14:50 UTC, fcollonval commented
bot please update documentation snapshots

2023-03-03 16:51 UTC, fcollonval commented
Kicking the CI

2023-03-06 18:23 UTC, krassowski reviewed
Could we use locator `options`?

2023-03-06 18:23 UTC, krassowski commented on galata/test/jupyterlab/metadataform.test.ts
> +    `.jp-NotebookTools .jp-Collapse .jp-Collapse-header:hasText('${label}')`
```suggestion
    '.jp-NotebookTools .jp-Collapse .jp-Collapse-header',
    {hasText: label}
```

2023-03-06 18:23 UTC, krassowski commented on galata/test/jupyterlab/metadataform.test.ts
> +      `.jp-NotebookTools .jp-Collapse .jp-Collapse-header:hasText('Extension metadata')`
```suggestion
      '.jp-NotebookTools .jp-Collapse .jp-Collapse-header',
      {hasText: 'Extension metadata'}
```

2023-03-09 14:41 UTC, fcollonval commented
bot please update documentation snapshots

2023-03-10 01:08 UTC, JasonWeill commented
bot please update documentation snapshots

2023-03-10 19:21 UTC, JasonWeill commented
please update galata snapshots

2023-03-11 14:21 UTC, krassowski approved these changes
Thank you @JasonWeill. I left one minor suggestion to further harmonise behaviour/improve UX.

2023-03-11 14:21 UTC, krassowski commented on packages/ui-components/style/collapse.css
> +}
```suggestion
  user-select: none;
}
```

One difference I noted when testing on binder is that when clicking on headers in property inspector the titles sometimes get selected whereas in extension manager or debugger this does not happen thanks to `user-select: none`.

2023-03-11 17:02 UTC, JasonWeill commented
bot please update documentation snapshots

2023-03-11 22:50 UTC, merged

2023-03-11 22:55 UTC, JasonWeill commented
@jtpio @fcollonval I'd like to test these changes with my team using a new alpha build. It's been about 9 days since 4.0.0a35 was released. What's the process to get 4.0.0a36 released from tip of `master`? Thanks!

2023-03-13 08:23 UTC, jtpio commented
@JasonWeill we use the Jupyter Releaser for making releases: https://github.com/jupyterlab/jupyterlab/blob/master/RELEASE.md#the-jupyterlab-release-process

There is no requirement of time between two releases, so there could be a new one yes.
Would you like to give it a try? You would need to configure the releaser tokens (more details in the releaser docs) and have maintainer access to `jupyterlab` on PyPI and `npm`. Happy to discuss on other mediums like Gitter to help set you up.

2023-03-13 08:41 UTC, fcollonval commented
> If you can make it today, it will be great - I was waiting for https://github.com/jupyterlab/jupyterlab/pull/13875 that is now ready to be merged. But require a release right after to get the CI green. So if you could merge it and release, it will be awesome.

2023-03-13 08:54 UTC, jtpio commented
FYI I just submitted https://github.com/jupyterlab/jupyterlab/pull/14176 to help make JupyterLab releases from the repo directly and to avoid setting up the tokens and the fork.