Implements #9005: Option to disable the autolink feature
jupyterlab/jupyterlab pull request #14068
Opened 2023-02-22 18:43 UTC by cccs-nik

## References

Implements #9005: Option to disable the autolink feature. I was going to create my own issue but found this existing one from 2020. I would like the same feature implemented. I manage a JupyterHub deployment for our organization where our users deal with malicious URLs that we don't want to be clickable when outputted.

## Code changes

An additional setting for the rendermime extension to skip URL replacement in the autolink function used by the text renderer.

## User-facing changes

A new setting for the rendermime extension:
![image](https://user-images.githubusercontent.com/68961854/220725691-d5c26412-ecda-4fa1-a5c6-64703036acc6.png)

The new setting would allow skipping URL replacement like so:
![image](https://user-images.githubusercontent.com/68961854/220726325-abe1abe8-9357-48e5-93b9-dcefcd4399e8.png)

## Backwards-incompatible changes

I think none.

2023-02-23 09:51 UTC, fcollonval reviewed
Thanks for the contribution @cccs-nik 

As the sanitizer is already part of available information (and this is somehow related), I was wondering if we could not extend `ISanitizer` to provide a new flag `autolink: boolean`. It will be connected to the settings in that plugin:

https://github.com/jupyterlab/jupyterlab/blob/3ecf75ac8eda5f11e55f318658577bba227ecdf6/packages/apputils-extension/src/index.ts#L615

This will make the code change much smaller with no need for signals.

2023-02-23 21:22 UTC, cccs-nik commented
I've modified it based on your suggestion. The code changes are indeed smaller. Let me know if this is what you had in mind and if you have any other suggestions.

Merci!

2023-02-24 14:54 UTC, fcollonval requested changes
Thanks @cccs-nik 

Tiny changes and a request: could you add unit tests there (you can use that text as example):

https://github.com/jupyterlab/jupyterlab/blob/a920f332d0b12d084588f672af3926fc7d31163d/packages/rendermime/test/factories.spec.ts#L121

2023-02-24 14:54 UTC, fcollonval commented on packages/rendermime-interfaces/src/index.ts
> +     * @returns Whether to replace URLs.
```suggestion
     * @returns Whether to replace URLs by HTML anchors.
```

2023-02-24 14:54 UTC, fcollonval commented on packages/apputils/src/tokens.ts
> +   * @returns Whether to replace URLs.
```suggestion
   * @returns Whether to replace URLs  by HTML anchors.
```

2023-02-24 14:54 UTC, fcollonval commented on packages/apputils/src/sanitizer.ts
> +   * @returns Whether to replace URLs.
```suggestion
   * @returns Whether to replace URLs by HTML anchors.
```

2023-02-24 14:54 UTC, fcollonval commented on packages/completer/src/widget.ts
> +      };
Let's simplify this:

```suggestion
      const sanitizer = this.sanitizer;
```

2023-02-24 14:54 UTC, fcollonval commented on packages/rendermime/src/renderers.ts
> +  replace: boolean
Let's shunt this method to avoid unnecessary regex lookup.

```suggestion
  content: string
```

2023-02-24 14:54 UTC, fcollonval commented on packages/rendermime/src/renderers.ts
> +  while (null != (match = webLinkRegex.exec(content)) && replace) {
```suggestion
  while (null != (match = webLinkRegex.exec(content))) {
```

2023-02-24 17:12 UTC, cccs-nik commented
Thanks for the quick reviews @fcollonval. I fixed the above, just need to add unit tests but I'll have to push that to later next week. I'll send a re-request review your way once that's done.

2023-03-13 09:24 UTC, fcollonval commented
Thanks @cccs-nik 

I realize that there is an inconsistency in interface inheritance for `ISanitizer` - it is defined in two places when it should not. Would you mind if I push a commit to remove that inconsistency? I would also make the new `getAutolink` optional to avoid api-changes in the mimetype renderer.

2023-03-13 13:42 UTC, cccs-nik commented
Yup feel free to push a commit for both of those changes! @fcollonval

2023-03-14 12:31 UTC, fcollonval approved these changes
Thanks for the patience @cccs-nik

2023-03-14 13:59 UTC, merged