Fix:Issue #13965 resolved. <code> block in the UI must not show now when there is an error installing any extension.
jupyterlab/jupyterlab pull request #14095
Opened 2023-02-27 08:15 UTC by doesnots

## References

## Code changes

## User-facing changes

## Backwards-incompatible changes

2023-03-01 22:23 UTC, andrii-i approved these changes
This looks good, follows suggestions, and fixes #13965. Thank you, @doesnots.

@doesnots could you please also fill out the template in this PRs header so that people looking at it in the future would be able to quickly see what this PR is about?

2023-03-01 22:35 UTC, andrii-i requested changes
There are 2 tests currently failing: 
* [Depreciated har-validator@5.1.5 library warning ](https://github.com/jupyterlab/jupyterlab/actions/runs/4281879501/jobs/7455444442) which does not seem to be related to this change
* [Linter fails](https://github.com/jupyterlab/jupyterlab/actions/runs/4281879501/jobs/7455446292). @doesnots could you please make sure you ran pre-commit hooks on this change? They should run linter and correct all linting problems

2023-03-02 08:54 UTC, jtpio commented on packages/extensionmanager/src/dialog.tsx
> +  entries.push(<p>{trans.__(`An error occurred installing "${name}."`)}</p>);
Looks like the dot could be moved:

```suggestion
  entries.push(<p>{trans.__(`An error occurred installing "${name}".`)}</p>);
```

2023-03-02 10:01 UTC, jtpio approved these changes
Thanks!

2023-03-02 10:01 UTC, merged