Suppresses header check inside frontmatter
jupyterlab/jupyterlab pull request #14203
Opened 2023-03-15 23:50 UTC by JasonWeill

## References

Fixes #14200.

## Code changes

Suppresses Markdown header check inside YAML frontmatter, defined as lines surrounded by `---` on a line by itself.

## User-facing changes

In the Markdown block below, `Summary` and `Motivation` are recognized as headings, and nothing in the frontmatter is.

```
---
title: Adopting a text-based diagram syntax in Jupyter Markdown
authors: (alphabetically) Nick Bollweg (@bollwyvl)
issue-number: 100
pr-number: 101
date-started: 2021-03-14
---

# Summary

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# Motivation

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

## Backwards-incompatible changes

None.

2023-03-16 00:45 UTC, bollwyvl commented
---
front: matter
---

^^^ that's some frontmatter

Ha, hadn't even looked at the implementation... figured it actually used the markdown parser or something. That's a lot of heuristics. But this is markdown, which seems to be _made_ entirely of heuristics.

The changed seems reasonable, but I imagine some more cases around the .rst-like/`setext` style of [headers](https://daringfireball.net/projects/markdown/syntax#header):


```md
---
front: matter
---

Not-front-matter
===

Really-not-front-matter
---

Not even looking
~~~

> ^^^ this is probably an alternate code block

```

2023-03-16 01:13 UTC, bollwyvl commented
Oh, and the (very whitespace-sensitive) "semantic break" that makes a `<hr/`>`:

```

---

```

2023-03-16 02:49 UTC, JasonWeill commented
@bollwyvl Since this is *front* matter, should we only do the frontmatter check once, on the very first line of the file? That would prevent the horizontal rule `---` from triggering this logic.

2023-03-16 09:41 UTC, fcollonval commented
thanks @JasonWeill 

> @bollwyvl Since this is _front_ matter, should we only do the frontmatter check once, on the very first line of the file? That would prevent the horizontal rule `---` from triggering this logic.

Yes we should only check for the very first line; switch to a logic:

1. Is there a header
2. Skip the header
3. Look for headings after the header

Another reason is that your current implementation will not work with the following case:

```
Title 1
---

Title 2
---
```

I'm pretty sure the current logic will escape the second title.

---

I'm :+1: for reusing the markdown parsing (especially as we are already parsing twice the string, once by CM and once by marked.js). But let's open a follow-up issue as it will require more complex changes.

2023-03-16 13:41 UTC, bollwyvl commented
Yep: I guess we're trying to match upstream GFM: here are some weird cases: https://gist.github.com/bollwyvl/84f19e4bcb3a6d5a8d23a26a5bcaf329

Here are some weird [edge cases](https://gist.github.com/bollwyvl/84f19e4bcb3a6d5a8d23a26a5bcaf329).

2023-03-17 07:15 UTC, fcollonval requested changes

2023-03-17 07:15 UTC, fcollonval commented on packages/toc/src/utils/markdown.ts
> +    if (line === '---' && (isFrontmatterBlock || lineIdx === 0)) {
Could we move this logic before the for loop line 69? Then you can enter the _regular_ parsing with `lineIdx` greater than 0 (aka after the header).

So the code will look like:

```typescript
// Skip frontmatter header if any

// ...

for (let lineIdx = lineAfterHeader; lineIdx < lines.length; lineIdx++) {
  // parsing for headings
}

2023-03-20 14:28 UTC, fcollonval approved these changes
Thanks @JasonWeill

2023-03-20 16:08 UTC, merged