Fix examples further to CodeMirror API change
jupyterlab/jupyterlab pull request #14293
Opened 2023-03-30 11:06 UTC by echarles

## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/14221

## Code changes

Update the cell and notebook examples

## User-facing changes

The outputs are now displayed as before for the `cell`, `notebook` and `console` examples..

![Untitled6](https://user-images.githubusercontent.com/226720/228817317-73e2056b-e70c-4c19-a3dc-f00f46351213.gif)

## Backwards-incompatible changes

None

2023-03-30 12:24 UTC, jtpio commented
Thanks @echarles for looking into it :+1: 

Looks like it needs a lint check, but looking good otherwise.

2023-03-30 14:39 UTC, echarles commented
Thx @jtpio. Just linted and pushed.

2023-03-30 16:35 UTC, fcollonval requested changes
Thanks @echarles 

I have one small comments and the releaser test needs to be fixed - the explicit dependency to `@jupyter/ydoc` should be provided in the examples package.json.

> the other test failures are due to flaky errors or are not the consequence of this particular PR.

2023-03-30 16:35 UTC, fcollonval commented on packages/codemirror-extension/src/services.tsx
> + * CodeMirror binding provider.
Could we keep a reference to what it is bound to CodeMirror?

```suggestion
 * CodeMirror shared model binding provider.
```

2023-03-30 16:59 UTC, echarles commented
> the explicit dependency to @jupyter/ydoc should be provided in the examples package.json.

thx for the review @fcollonval - I have added the needed deps.

2023-03-31 07:06 UTC, fcollonval commented
Almost there @echarles, you need to run `jlpm install` to update the yarn.lock file and this PR will be good to go.

> As you are submitting from an org, I unfortunately cannot help without those changes.

2023-03-31 07:13 UTC, echarles commented
@fcollonval Thx for your help and patience :)

2023-03-31 08:52 UTC, fcollonval approved these changes
Thanks @echarles 

> CI failures are not related

2023-03-31 08:52 UTC, merged