Add signal when an item factory is added to the toolbar
jupyterlab/jupyterlab pull request #14376
Opened 2023-04-13 10:08 UTC by brichet

See https://github.com/jupyterlab/jupyterlab/issues/14366 for context.

## References

Fixes https://github.com/jupyterlab/jupyterlab/issues/14366
The issue was first notified in https://github.com/jupyter/notebook/pull/6838

## Code changes

Adds a signal in `ToolbarWidgetRegistry`, which is emitted when an item factory is added to the registry.
This signal is caught by the `toolbarFactory` to render again the widget.

## User-facing changes

None

## Backwards-incompatible changes

None

2023-04-13 16:35 UTC, fcollonval requested changes
Thanks @brichet I think there is a small typo but otherwise it looks good.

2023-04-13 16:35 UTC, fcollonval commented on packages/apputils/src/toolbar/factory.ts
> +      if (itemIndex >= -1) {
I guess it is:

```suggestion
      if (itemIndex >= 0) {
```

2023-04-13 16:39 UTC, brichet commented on packages/apputils/src/toolbar/factory.ts
> +      if (itemIndex >= -1) {
Thanks

2023-04-14 06:42 UTC, jtpio commented
Thanks @brichet!

Wondering if there could be other situations than just toolbar items that could be affected by this new caching logic of the settings?

2023-04-14 07:27 UTC, brichet commented
> Wondering if there could be other situations than just toolbar items that could be affected by this new caching logic of the settings?

This is hard to say, this is really an indirect effect, and there is probably no test on that behavior.
Actually, we were lucky it worked without trouble until now. It is likely that adding dependencies on other plugins with long loading times could have produced the same issue.

2023-04-14 08:55 UTC, merged