Backport PR #14414 on branch 3.6.x (Fix CI: remove/update broken docs links)
jupyterlab/jupyterlab pull request #14538
Opened 2023-05-14 20:43 UTC by krassowski

## References

Backport PR #14414: Fix CI: remove/update broken docs links

2023-05-16 11:05 UTC, fcollonval requested changes
Here is a suggestion to fix the integrity check

2023-05-16 11:05 UTC, fcollonval commented on packages/services/README.md
> +[API Docs](https://jupyterlab.readthedocs.io/en/latest/api/)
```suggestion
[API Docs](https://jupyterlab.readthedocs.io/en/3.6.x/api/)
```

2023-05-20 10:57 UTC, krassowski commented on packages/services/README.md
> +[API Docs](https://jupyterlab.readthedocs.io/en/latest/api/)
Thank you!

2023-05-20 10:59 UTC, krassowski commented
The check is passing now. The remaining failures are unrelated - merging.

2023-05-20 10:59 UTC, merged