Extension tutorial enhancement
jupyterlab/jupyterlab pull request #14669
Opened 2023-06-11 14:45 UTC by coriegulik

## References
https://github.com/jupyterlab/jupyterlab/issues/13373

## Code changes
emphasized importance of the conda environment in the extension process. 

## User-facing changes
If user uses a container instead of a conda environment, build issues arise.

## Backwards-incompatible changes
none

2023-06-12 08:23 UTC, fcollonval requested changes
Thanks  @coriegulik 

I have some suggestions.

2023-06-12 08:23 UTC, fcollonval commented on docs/source/developer/contributing.rst
> +macOS, or Windows Subsystem for Linux. If using Windows, we recommend installing `Anaconda for windows <https://www.anaconda.com/download>`__ and then using the Anaconda command prompt for all instal
Could you rebase your branch to separate the changes as this is part of another PR (that got merge - congrats for that).

2023-09-27 07:55 UTC, krassowski commented
@coriegulik just checking if you are still interested in driving this forward. There are two suggestions above.

2023-12-20 18:10 UTC, JasonWeill commented on docs/source/developer/contributing.rst
> +macOS, or Windows Subsystem for Linux. If using Windows, we recommend installing `Anaconda for windows <https://www.anaconda.com/download>`__ and then using the Anaconda command prompt for all instal
```suggestion
macOS, or Windows Subsystem for Linux. If you use Windows, we recommend installing `Anaconda for Windows <https://www.anaconda.com/download>`__ and then using the Anaconda command prompt for all installation steps.
```

2023-12-20 18:10 UTC, JasonWeill commented on docs/source/extension/extension_tutorial.rst
> +Building an extension in JupyterLab involves a number of moving parts: node, yarn, tsc, pip, hatch, and a large number of JupyterLab and utility modules. Each of these are under active development, a
```suggestion
Building an extension for JupyterLab involves JavaScript and Python development tools. We recommend that inexperienced developers develop extensions using conda environments or, if you use Visual Studio Code, to use the [VS Code configuration template for JupyterLab](https://github.com/jupyterlab/vscode-config-template).
```

2024-07-15 11:14 UTC, krassowski commented
@coriegulik are you interested in following up on the suggestions and requested changes or should we close this PR?

2025-10-05 00:04 UTC, krassowski commented
Closing as stale since there are merge conflicts and no reply was received.

2025-10-05 00:04 UTC, closed without merging