fix: out of order headings display in toc
jupyterlab/jupyterlab pull request #14753
Opened 2023-06-25 20:52 UTC by skyetim

## References

Fix #14574 

## Code changes

The current codes assume only one tree. The updated code fixes the DFS in `TableOfContentsTree.buildTree` to support multiple trees (out of order headings). 

## User-facing changes

Before
![image](https://github.com/jupyterlab/jupyterlab/assets/16680640/e7aba277-bac9-4daa-82e7-55521a7602e5)

After
![image](https://github.com/jupyterlab/jupyterlab/assets/16680640/288a7220-7a3a-444a-8278-e6a78aa9b64d)

## Backwards-incompatible changes
None

2023-06-27 07:18 UTC, fcollonval commented
bot please update galata snapshots

2023-06-28 14:27 UTC, fcollonval requested changes
Thanks for updating the test @skyetim 

So there is actually a small bug; the collapse triangle is shown for all headings even those without children. I made a suggestion to fix it.

2023-06-28 14:27 UTC, fcollonval commented on packages/toc/src/toctree.tsx
> +          {children}
Ok there is a bug for leaf element that should be fixed by:

```suggestion
          {children.length ? children : null}
```

2023-06-29 03:13 UTC, skyetim commented
bot please update galata snapshots

2023-07-02 15:15 UTC, krassowski commented
Closing and re-opening to trigger CI build (stalled after bot update).

2023-07-07 12:22 UTC, krassowski commented on galata/test/jupyterlab/notebook-run.test.ts-snapshots/notebook-panel-1-jupyterlab-linux.png
This needs to be reverted.

2023-07-09 00:34 UTC, skyetim commented on galata/test/jupyterlab/toc-running.test.ts-snapshots/toc-running-indicators-jupyterlab-linux.png
I guess this needs to be removed too?

2023-07-09 09:27 UTC, krassowski commented on galata/test/jupyterlab/toc-running.test.ts-snapshots/toc-running-indicators-jupyterlab-linux.png
Either way is fine, it seems that visual regression tests pass now except for one known issue.

2023-07-09 09:30 UTC, krassowski approved these changes
I believe this one is good to go but will wait with merging in case @fcollonval wants to have another look.

2023-07-23 09:44 UTC, fcollonval approved these changes
Thanks @skyetim

2023-07-23 09:44 UTC, merged

2023-07-23 09:45 UTC, fcollonval commented
@meeseeksdev please backport to 4.0.x