Move opening help resources to a separate plugin
jupyterlab/jupyterlab pull request #14837
Opened 2023-07-17 13:31 UTC by jtpio

## References

This should help with https://github.com/jupyter/notebook/issues/6963 and https://github.com/jupyter/notebook/pull/6968

## Code changes

Move the command that opens help resources in the `main` area in IFrames or new browser tabs to a new plugin.

That way, downstream applications like Notebook 7 can choose to not include this plugin and provide their own instead.

## User-facing changes

None

## Backwards-incompatible changes

None

2023-07-20 13:57 UTC, fcollonval requested changes
Thanks @jtpio 

I spotted a small error. But otherwise it looks good to go.

However I'm not in favor of backporting it to 4.0.x as the new plugin defines a command from the old `resources` plugin. So if someone disable the `resources`, it may create a conflict by providing its own implementation of that command or simply adding a command he does not want.

2023-07-20 13:57 UTC, fcollonval commented on packages/help-extension/src/index.tsx
> +    restorer: ILayoutRestorer | null
Not requested any more

```suggestion
```

2023-07-20 15:47 UTC, jtpio commented on packages/help-extension/src/index.tsx
> +    restorer: ILayoutRestorer | null
Thanks for catching this :+1:

2023-07-23 09:39 UTC, fcollonval approved these changes
Thanks @jtpio 

Do you think you could add a note in the CHANGELOG as part of this PR so we don't forget to do it when releasing?

2023-07-28 06:03 UTC, jtpio commented on CHANGELOG.md
> +## v4.1
Let's see if CI still passes with this new section.

2023-07-31 13:51 UTC, fcollonval commented
Thanks @jtpio 

> Remaining CI failures are not related

2023-07-31 13:51 UTC, merged