Bugfix for #14458
jupyterlab/jupyterlab pull request #14870
Opened 2023-07-23 21:43 UTC by alewilliam789

## References

#14458 

## Code changes

Changes HTML/CSS to match the Text widget from ipywidgets and follows same styles.

## User-facing changes

The input widget now matches the Text Widget in the output area.

Input before changes: 
![image](https://github.com/jupyterlab/jupyterlab/assets/82249653/1e025dd7-5858-4579-afb3-136f36928f66)

Input after changes:
![image](https://github.com/jupyterlab/jupyterlab/assets/82249653/7748b382-28ce-4eda-a840-cd2cba142ace)

## Backwards-incompatible changes

No it really only styles the Stdin widget.

2023-07-31 13:48 UTC, fcollonval requested changes
Thanks @alewilliam789 

One of the integration test failing is legit:

This is the test failing: https://github.com/jupyterlab/jupyterlab/blob/e2cdaf1f01457195a7fb73bd25924a543343c78c/galata/test/jupyterlab/outputarea-stdin.test.ts#L11

The reason is the styling that changes (as expected :wink:) - before is left / this PR is right

![image](https://github.com/jupyterlab/jupyterlab/assets/8435071/15cc12bf-de67-4bfb-845e-b3d5140f5e98)

That case makes it unclear the box can be edited. Would you mind improving the styling for that case?

You can find the result of the integration test (including a video of it as artifact `jupyterlab-galata-test-assets` at the bottom of https://github.com/jupyterlab/jupyterlab/actions/runs/5646058234)

2023-08-16 16:27 UTC, alewilliam789 commented
@fcollonval At this point it looks like the only reason this last UI test is failing is because the snapshot being used has the old styling. After reading the Galata README it looks like new benchmarks are made after an approved PR review and it is requested in the code review correct?

2023-08-28 17:05 UTC, ohrely commented
@alewilliam789 Thanks for this contribution!  The failing visual regression test is something you can fix locally by taking the test's output screenshot and using it to replace the reference screenshot.  Alternatively you can add "please update snapshots" to the PR description to trigger a bot to do this for you.

I just rebased this branch, so you'll want to pull the current state of the PR before making further changes.  It looks like there's a lint issue turned up in one of the tests that will need to be addressed before merge.

2023-09-01 05:12 UTC, krassowski commented on galata/test/jupyterlab/outputarea-stdin.test.ts-snapshots/stdin-history-search-jupyterlab-linux.png
This is definitely nicer, but the wide indent which almost centers the input on smaller screens seems a bit odd to me.

2024-02-16 15:33 UTC, closed without merging