fix: heading doesn't scroll into view
jupyterlab/jupyterlab pull request #14884
Opened 2023-07-30 19:50 UTC by skyetim

## References
Fix #14591 

## Code changes

Previously, the element of each cell is stored in a map which relies on an async function `getIdForHeading`. The bug occurs when the element isn't computed yet. The code changes remove this map and find the element on the fly. 

## User-facing changes

Bug is fixed and heading will scroll into view as intended. 

## Backwards-incompatible changes

None

2023-08-09 07:43 UTC, fcollonval requested changes
Thanks a lot @skyetim for working on this.

Unfortunately this does not solve the issue. The trouble with a cell being in edit mode is that the rendered markdown is not in the DOM. So `findHeadingElement` will never return an `element`.

What we should be added is, in case `el` is `null`, we should scroll to the cell.

> This can be achieve by using `widget.content.scrollToItem(widget.content.activeCellIndex)`.

We can even go a step further by selecting the heading in the cell editor with something like:

```ts
if (widget.content.mode === 'edit' && cell.model.type === 'markdown') {
    const allMatches = await TextSearchEngine.search(
      new RegExp(`^${'#'.repeat(heading.level)} ${heading.text}$`),
      cell.model.sharedModel.getSource()
    );
    const first = allMatches[0]
    if (first) {
      const editor = cell.editor!;
      editor.setSelection({
        start: editor.getPositionAt(first.position)!,
        end: editor.getPositionAt(first.position + first.text.length)!
      });
    }
}
```

Would you be willing to change this PR? Could you also restore the mapping because it is costly to generate the `id` from the cell content (it requires rendering the markdown).

2023-09-06 19:35 UTC, krassowski commented
@skyetim did you have a chance to get back to this? If not, does it make sense to switch this PR to draft for now?

2023-09-06 22:57 UTC, skyetim commented
It was quite a busy month. I will revisit this this month.

2023-10-10 22:46 UTC, krassowski commented
Should we close this PS as superseded by #15184 @skyetim? Thanks again for starting this!

2023-10-10 22:50 UTC, skyetim commented
Makes sense. @parmentelat Thanks for taking over.

2023-10-10 22:50 UTC, closed without merging