changed css styling for links
jupyterlab/jupyterlab pull request #14914
Opened 2023-08-03 12:04 UTC by s596757

Made CSS changes in order to ensure all links are visually distinct:

All links are now underlined as standard expectation based on:
https://www.w3.org/TR/html401/struct/links.html
When you hover over a link, the link is both bold and underlined
Link that has been visited changes to a grey color
Tested visually
Based on feedback from UX engineer

Ticket based on issue https://github.com/jupyterlab/jupyterlab/issues/9399 Text issue number 2

Please provide additional feedback and notes on your definition of visually distinct

2023-08-08 18:37 UTC, krassowski requested changes
> All links are now underlined as standard expectation based on: https://www.w3.org/TR/html401/struct/links.html

This is not what the document linked to says - it says *for example* underlined

> When you hover over a link, the link is both bold and underlined

I do not agree with this design direction. All of the web uses underline on hover. Using bold on hover will lead to layout shifts. So this is -1 from me here.

> Link that has been visited changes to a grey color

Changing colour to indicate visited links is probably fine, but I would request to add a semantic variable so that themes (and users) can override it easily.

2023-08-08 18:37 UTC, krassowski commented on packages/rendermime/style/base.css
> +  color: var(--jp-content-font-color3);
Can you define a semantic variable, e.g. `--jp-content-link-visited-color` or `--jp-content-visited-link-color` and use it where needed to allow overriding the colour choice and ensure consistency?

```suggestion
  color: var(--jp-content-link-visited-color);
```

2023-08-09 17:51 UTC, krassowski requested changes
My previous opinion that we should not switch to underline/bold still stands. However, I do think that maybe it could be opt-in via a setting (which would involve creating a dedicated accessibility package).

2023-08-09 17:51 UTC, krassowski commented on packages/rendermime/style/base.css
> +  color: var(--jp-content-font-color3);
Should use `var(--jp-content-link-visited-color)` too.

2023-08-09 17:51 UTC, krassowski commented on packages/extensionmanager/style/base.css
> +  color: var(--jp-content-font-color3);
Should use `var(--jp-content-link-visited-color)` too.

2023-08-09 17:51 UTC, krassowski commented on packages/rendermime/style/base.css
> +  color: var(--jp-content-link-visited-color);
I do not see a definition for this variable, it needs to be added.

2023-08-20 20:04 UTC, krassowski commented
@s596757 the lint job is failing can you run `jlpm run prettier`?

2023-08-21 11:56 UTC, s596757 commented
> jlpm run prettier

I have run it :)

2023-09-07 21:05 UTC, krassowski commented
@s596757 did you commit and push changes?  The [lint check](https://github.com/jupyterlab/jupyterlab/actions/runs/5819136652/job/15776958467?pr=14914) is still failing with:

```
Checking formatting...
[warn] packages/rendermime/style/base.css
[warn] packages/theme-dark-extension/style/variables.css
[warn] Code style issues found in 2 files. Run Prettier to fix.
+ echo 'Please run `jlpm run prettier` locally and push changes'
Please run `jlpm run prettier` locally and push changes
```

2023-09-23 10:55 UTC, krassowski commented on packages/theme-dark-extension/style/variables.css
> +  --jp-content-link-hover-color: var(--md-blue-400)
Educated guess that this is why the lint check is failing.

```suggestion
  --jp-content-link-hover-color: var(--md-blue-400);
```

2023-09-23 10:57 UTC, krassowski commented
@s596757 I addressed the lint failure for you, can you add before/after screenshots in both light and dark mode to the top-level comment, please?

2023-09-29 16:22 UTC, krassowski commented
Closing in favour of #15181.

2023-09-29 16:22 UTC, closed without merging