updated link color
jupyterlab/jupyterlab pull request #14995
Opened 2023-08-20 15:17 UTC by jahir-raihan

## References
 Issue : #14166

## Code changes

- [x] Changed colour and text decoration of links - Base level

## User-facing changes

**Problem was with Link colour which was mentioned in #14166**

**Note: The Screenshot below is maybe from a older version. When i checked for the "Trust Notebook" widget, there was no link colour or styling on the link.**

**I'm not sure it may even break other parts of the code. If that happens, i'll sure look into it.**
Screenshot from issue : 

![](https://user-images.githubusercontent.com/26686070/224459732-6cfaa664-f188-432f-ba65-5eb4175bd62b.png)

Screenshot from current version:
![Screenshot 2023-08-20 at 9 15 25 PM](https://github.com/jupyterlab/jupyterlab/assets/78207450/646f15eb-329f-4087-85e4-21984c5484ef)

Screenshot after fixing styling : 

![Screenshot 2023-08-20 at 9 00 34 PM](https://github.com/jupyterlab/jupyterlab/assets/78207450/42b9ba1a-84d2-4c6f-8e4d-bc4333fb76d1)

## Backwards-incompatible changes

No Changes

2023-08-20 20:06 UTC, krassowski commented
Related PR which adds a new colour variable for hover: #14914.

2023-08-27 00:09 UTC, krassowski requested changes
Thank you for working on it. If you mean to change the colour of the link in dialog, please modify the variable used in `.jp-Dialog-content a` sector rather than changing global styles.

2023-08-27 02:08 UTC, jahir-raihan commented
@krassowski Thank you for pointing it out.

2023-11-02 15:50 UTC, krassowski commented
@jahir-raihan are you still interested in finishing this one?

2023-11-02 16:27 UTC, jahir-raihan commented
> @jahir-raihan are you still interested in finishing this one?

Hello, You can close this one.  I will open a new pull request upon this issue after ICPC regional. Sorry for being late.

2023-11-02 16:28 UTC, closed without merging