Fix update button in extension manager
jupyterlab/jupyterlab pull request #15331
Opened 2023-10-30 16:11 UTC by nbowditch-einblick

## References

### https://github.com/jupyterlab/jupyterlab/issues/15316 Extension manager "Update to" button does not update extensions 

## Code changes

- Added missing `extension_version` parameter to the backend request when the "Update to ###" button is clicked in the extension manager.
   - This was done by adding a `useLatestVersion` parameter to the `install` action on the front-end model. When `true`, the request adds the `extension_version` property to the request body using `entry.latest_version`.
   - Generic front-end action functions (eg `performAction` and `onAction`) now have an optional `actionOptions` parameter where additional parameters/specifications can be defined

## User-facing changes

None

## Backwards-incompatible changes

None

2023-10-31 14:08 UTC, fcollonval requested changes
Thanks a lot for working on this @nbowditch-einblick 

I would like to propose a slightly different approach to pass directly the version as this is supported by the backend and may provide more flexibility.

2023-10-31 14:08 UTC, fcollonval commented on packages/extensionmanager/src/model.ts
> +  useLatestVersion?: boolean;
As the backend support a specific version, let's add that as an option:

```suggestion
  /**
   * Install the version of the entry.
   *
   * #### Note
   * This is ignored by all actions except install.
   */
  useVersion?: string;
```

2023-10-31 14:08 UTC, fcollonval commented on packages/extensionmanager/src/widget.tsx
> +                              useLatestVersion: true
This will become:

```suggestion
                              useVersion: entry.latest_version
```

2023-10-31 14:08 UTC, fcollonval commented on packages/extensionmanager/src/widget.tsx
> +      actionOptions: IActionOptions
let's make this one optional:

```suggestion
      actionOptions?: IActionOptions
```

2023-10-31 14:08 UTC, fcollonval commented on packages/extensionmanager/src/model.ts
> +    useLatestVersion: boolean = false
We prefer to use object that are more flexible to extend an API in a non-breaking way.

```suggestion
    options: { useVersion?: string }
```

> e.g. in the future we may want to add an option `force` to the install action.

2023-10-31 14:08 UTC, fcollonval commented on packages/extensionmanager/src/model.ts
> +    await this.performAction('install', entry, { useLatestVersion }).then(
```suggestion
    await this.performAction('install', entry, options).then(
```

2023-10-31 14:08 UTC, fcollonval commented on packages/extensionmanager/src/model.ts
> +    }
```suggestion
    if (actionOptions.useVersion) {
      bodyJson['extension_version'] = actionOptions.useVersion;
    }
```

2023-10-31 14:08 UTC, fcollonval commented on packages/extensionmanager/src/widget.tsx
> +        return this.model.install(entry, actionOptions.useLatestVersion);
```suggestion
        return this.model.install(entry, actionOptions);
```

2023-10-31 14:08 UTC, fcollonval commented on packages/extensionmanager/src/widget.tsx
> +        return this.model.install(entry, actionOptions.useLatestVersion);
```suggestion
        return this.model.install(entry, actionOptions);
```

2023-10-31 14:29 UTC, nbowditch-einblick commented on packages/extensionmanager/src/model.ts
> +    options: { useVersion?: string } = {}
@fcollonval - Thanks for the review! I also gave a default value to this parameter here, but let me know if you'd rather it not be optional.

2023-10-31 16:34 UTC, fcollonval reviewed
Thanks @nbowditch-einblick 

Would you be willing to add a test for this?

You can add it in that file: https://github.com/jupyterlab/jupyterlab/blob/b835dd9acc2a00e2ee12450b9bc2b988ad789bd3/galata/test/documentation/extension_manager.test.ts

Starting by duplicating that test:

https://github.com/jupyterlab/jupyterlab/blob/b835dd9acc2a00e2ee12450b9bc2b988ad789bd3/galata/test/documentation/extension_manager.test.ts#L54

To fake an available update; you will need to set a newer version for one of the two packages in https://github.com/jupyterlab/jupyterlab/blob/main/galata/test/documentation/data/extensions.json

The test will look like:

```ts
   const waitRequest = page.waitForRequest(request => {
     if(request.method() !== 'POST' || !galata.Routes.extensions.test(request.url()) {
       return false;
     }
     const data = request.postDataJSON();
     return data.cmd === 'install' && data.extension_name === '...' && data.extension_version === '...';
   });
   await page.getByRole('button', { name: 'Update to <the fake version you set>'}).click();
   await waitRequest

2023-11-03 15:56 UTC, fcollonval commented on galata/test/documentation/extension_manager.test.ts
> +  });
:rocket:

2023-11-06 21:28 UTC, krassowski approved these changes
Looks good to me. I will wait with merging to allow @fcollonval to take another look.

> `test/jupyterlab/kernel.test.ts:108:9 › Kernel › Console › Should not ask kernel when creating console from launcher` failure is unrelated and is getting addressed in #15355

2023-11-07 14:53 UTC, nbowditch-einblick commented
@krassowski - thanks for taking a look! please let me know if I can do anything to update the branch, I wasn't sure if you guys prefer me doing a merge or rebase, or just taking care of it yourselves before merging

2023-11-08 17:32 UTC, fcollonval approved these changes
Thanks @nbowditch-einblick !

Let's merge

2023-11-08 17:32 UTC, merged

2023-11-08 22:06 UTC, krassowski commented
@meeseeksdev please backport to 4.0.x