Reopen recently opened/closed files and modal navigation
jupyterlab/jupyterlab pull request #15483
Opened 2023-12-04 01:00 UTC by krassowski

## References

- Closes https://github.com/jupyterlab/jupyterlab/issues/5924
- Closes https://github.com/jupyterlab/jupyterlab/issues/15293
- Closes https://github.com/jupyterlab/jupyterlab/issues/11613
- Upstream discussion https://github.com/jupyterlab-contrib/jupyterlab-recents/issues/10

Punchlist
- [x] galata tests
- [x] add an icon [↗] to sidebar

## Code changes

Compared to `jupyterlab-recents` extension:

<details>

- remove polling for validation of paths; this was generating many background requests and was deemed undesirable overhead if we were to increase the number of requests by a factor of 10 (even though these were lightweight GET requests)
- do not send a get request to fetch the model/content type of the document for the that the user switch to - we already have it available at hand now thanks to integration directly into docmanager (this is not public/not emitted by the signal which is why the extension had to have this sub-optimal implementation)
- path validation is now conducted when opening the sub-menu, and when clicking on the file, limiting any overhead to the users of the feature
- when an item is discovered to be invalid after submenu was opened it will not be removed but greyed out to avoid jitter and user accidentally clicking a wrong item
- split recents into "recently opened" and "recently closed"
- use `IFileBrowserCommands` to explicitly depend on the availability of the filebrowser to open directories (and to fallback to document manager command if filebrowser does not provide such token

Because rather than adding a new package the extension gets integrated on the lower level by adding separate plugins to relevant existing packages (document manager, main menu) merging git history did no make much sense; instead the autorship was preserved by using `Co-authored-by` feature.

</details>

## User-facing changes

### Open Recent submenu

![image](https://github.com/krassowski/jupyterlab/assets/5832902/7f822545-67c7-4ebf-a4c2-fbce45c61596)

### Recently closed in the sidebar

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/c91beb1c-d803-4238-8666-f17c8038ec95)

Also seen is the [↗] button to open modal

### Reopen modal

![reopen-widget-2](https://github.com/krassowski/jupyterlab/assets/5832902/160366fb-f258-4dcd-aedf-70583aad779a)

## Backwards-incompatible changes

None.

> File browsers are encouraged to implement `IFileBrowserCommands` which was previously a no-op; if they don't then the recents menu will not show the directories.

2023-12-29 18:01 UTC, krassowski commented
Any suggestions on alternative shortcuts we could use?

> A part of me wishes that we had two sets of shortcuts: one for JupyterLab Desktop and one for when running in a standard browser.

2024-01-15 12:03 UTC, krassowski commented
For now switching to <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>A</kbd> as it is not used by major browsers/operating systems as per https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts

2024-01-15 15:09 UTC, krassowski commented
bot please update snapshots

2024-01-16 17:03 UTC, krassowski commented
bot please update documentation snapshots

2024-02-22 10:56 UTC, jtpio commented on packages/docmanager-extension/schema/plugin.json
> +    "maximalRecents": {
Another suggestion for the name of this setting:

```suggestion
    "maxNumberRecents": {
```

2024-03-08 15:53 UTC, fcollonval requested changes
Thanks a lot for this @krassowski 

I have some minor suggestions.

2024-03-11 11:00 UTC, krassowski commented on packages/docmanager/src/recents.ts
> +    this._saveRoutine = setTimeout(async () => {
Good catch, done in 63c3e30fa79d0d327267dd164cb47fb8ea2f811d

2024-03-20 16:34 UTC, fcollonval approved these changes
Thanks @krassowski 

I have an optional suggestion.

2024-03-20 16:34 UTC, fcollonval commented on packages/docmanager/src/recents.ts
> +export class RecentsManager implements IRecentsManager, IDisposable {
I guess this is not needed any longer, isn't it?

```suggestion
export class RecentsManager implements IRecentsManager {
```

2024-03-20 17:57 UTC, krassowski commented on packages/docmanager/src/recents.ts
> +import { IDisposable } from '@lumino/disposable';
```suggestion
```

2024-03-20 19:17 UTC, krassowski commented
Snapshots will need updating after merging. I think one of the docs snapshots needs some work in general.

2024-03-21 11:10 UTC, krassowski commented
but please update documentation snapshots

2024-03-21 15:33 UTC, merged