Use toolkit search input for all search inputs: filebrowser, extension manager, debugger kernel source
jupyterlab/jupyterlab pull request #16046
Opened 2024-03-23 19:27 UTC by Mehak261124

**Issue:**  
The UI in JupyterLab is displaying differently after integrating the Search Input component from the Jupyter Toolkit in various extensions like the file browser, extension manager, and debugger kernel source.

**Background:**  
I utilised React components from the Jupyter Toolkit, which are wrappers over web components made using the Fast Foundation's Open UI system. These components are based on a template slot mechanism, as shown in their Storybook documentation. I modified the LabIcon React component to accept a slot as a prop and set the slot attribute to the LabIcon's container.

**Screenshots:** 
1.Search extension before
![Before1](https://github.com/jupyterlab/jupyterlab/assets/145124929/6d2db52e-7b7b-4e3a-9b98-3d61d7d703f4)

2. File explorer search before
![Before2](https://github.com/jupyterlab/jupyterlab/assets/145124929/0e8f7a48-84c5-4fe8-a5d3-c51fb5c46c63)

4. Search extension after
![After1](https://github.com/jupyterlab/jupyterlab/assets/145124929/896cd34c-58ab-488a-ba59-2a14cd306f40)

5.File explorer search after
<img width="1440" alt="AFTER2" src="https://github.com/jupyterlab/jupyterlab/assets/145124929/e7866e19-7cb3-4b09-bbcb-4663e92babcd">

2024-03-25 10:16 UTC, krassowski submitted a review, later dismissed
Thanks for opening a cleaned up PR @Mehak261124!

Updating the branch should resolve failing `Linux Tests / Linux (examples, 3.11) (pull_request) `.

The visual regression highlight caught that there are some potentiallly unused CSS rules, worth taking a look across the board if some input-related rules from the previous implementation of search boxes can be safely deleted:
```
1 out of 23 CSS rules for [ 'jp-DirListing', 'jp-FileBrowser' ] may be unused: [ '.jp-FileBrowser-filterBox input' ]
```

Snapshots appear to need updating.

2024-03-25 15:54 UTC, Mehak261124 commented
thank you so much, @krassowski  
i am updating the PR..

2024-04-04 15:07 UTC, fcollonval commented
Hey @Mehak261124 

Regarding the test checking the content of the search component, you can make the following changes:

```patch
-    await page.locator('.jp-PluginList .jp-FilterBox input').inputValue()
+    await page.locator('.jp-PluginList jp-search').evaluate(elem => 
+      (elem as any).value
+    )
```

> This is taken from the test _'Open the settings editor with a specific search query'_

The test _test-jupyterlab-readonly-test-readonly-status-test-readonly-status-jupyterlab_ should be ok. It's the reference snapshot that must be changes because it is slightly gray.

The usage tests should be fixed once you rebase the PR.

2024-04-04 15:11 UTC, fcollonval commented on packages/ui-components/src/icon/labicon.tsx
> +    slot?: 'end' | 'start' | null;
let's allow any string here as slot is not specified in details.

```suggestion
    slot?: string | null;
```

2024-04-05 07:33 UTC, fcollonval commented
My comments yesterday were quite direct. But to provide some background on the fix for the integration test, the web component hides its internal nodes. So the easiest work around is to evaluate a function on the web component directly. In particular for this case, we are interested in the attribute `value` of the search component. Hence the usage of the test method `page.locator('...').evaluate(<JS function to be evaluate in the page>)`.

2024-04-05 07:34 UTC, fcollonval commented
Important note: you will need to merge the main branch (or rebase this branch) to resolve the conflict and activate the CI jobs.

2024-04-05 08:00 UTC, Mehak261124 commented
> My comments yesterday were quite direct. But to provide some background on the fix for the integration test, the web component hides its internal nodes. So the easiest work around is to evaluate a function on the web component directly. In particular for this case, we are interested in the attribute `value` of the search component. Hence the usage of the test method `page.locator('...').evaluate(<JS function to be evaluate in the page>)`.

thanks, have made the required changes, have merged upstream main :)

2024-04-11 19:12 UTC, fcollonval requested changes
Thanks @Mehak261124 

We are almost there. I restarted the failing jobs that are not related to integration tests. And for those, I wrote suggestions on how to fix them.

2024-04-11 19:12 UTC, fcollonval commented on galata/test/documentation/customization.test.ts-snapshots/default-terminal-position-single-documentation-linux.png
The updated snapshot is not correct. We should see the prompt:

![image](https://github.com/jupyterlab/jupyterlab/assets/8435071/001f3a4e-7465-408c-a902-ae8c1d59e579)

2024-04-11 19:12 UTC, fcollonval commented on galata/test/jupyterlab/notebook-run.test.ts-snapshots/notebook-panel-1-jupyterlab-linux.png
Could you undo this change?

The better reference snapshot is without the cell toolbar:

![image](https://github.com/jupyterlab/jupyterlab/assets/8435071/34c2f0fd-017f-4485-81f9-4f522394833f)

2024-04-16 10:02 UTC, fcollonval commented
@Mehak261124 I took the liberty to help you finishing this one as the number of snapshots being changed makes this PR though to conclude with other PRs changing parts of the UI. The current state is not yet good as I'm pretty sure that the examples snapshots will need to be updated as well as galata/test/documentation/custom_css.test.ts-snapshots/custom-css-main-documentation-linux.png.
I'll try to push it through the finish line today as code wise the PR is very good.

2024-04-16 10:50 UTC, Mehak261124 commented
Thanku so much @fcollonval

2024-04-16 12:43 UTC, fcollonval approved these changes
Thanks a lot for the patience @Mehak261124 

We should be good to go - but let's wait for the CI results.

2024-04-16 15:08 UTC, merged

2024-04-16 22:30 UTC, Mehak261124 commented
Thank you so much, @fcollonval and @krassowski for all your guidance and support throughout this process.