Use toolkit button for all buttons: Dialog, extension manager, notification, running tabs
jupyterlab/jupyterlab pull request #16419
Opened 2024-06-03 16:40 UTC by Mehak261124

**Problem Statement:**
Use toolkit button for all buttons: Dialog, extension manager, notification, running tabs.

**Description:**
**Issue:**
Inconsistencies have arisen in the user interface across various JupyterLab extensions, including the Dialog, Extension Manager, Notification Center, and Running Tabs. 

**Background:**
The aim of this update is to standardize the UI elements across JupyterLab by utilizing the Button component from the Jupyter Toolkit. The Jupyter Toolkit's components are built on the Fast Foundation's Open UI system and are designed to provide a consistent look and enhanced accessibility across web applications.

The Button component was specifically integrated into several core components and extensions of JupyterLab to align with modern design practices and ensure UI consistency. Changes were made in the following files:

**widget.tsx:** Updated the Extension Manager's buttons to utilize the Button component from the Jupyter Toolkit, replacing previous implementations. This change ensures that all buttons within the Extension Manager now have a uniform appearance and behavior.
**dialog.tsx:** Employed Button in dialog actions, replacing previous HTML button elements. This standardizes dialog interactions throughout the application.
**notificationplugin.tsx:** Applied Button in notification actions to unify notification interaction points, ensuring consistent user experience across various notifications.
These updates help streamline component maintenance, improve stylistic consistency, and upgrade the overall user experience.

**Screenshots:**
Extensionmanager Button Before
![Before](https://github.com/Mehak261124/jupyterlab/assets/145124929/b7f0c99d-81cc-41d7-a3bd-a3d93619401c)

Extensionmanager Button After
![After](https://github.com/Mehak261124/jupyterlab/assets/145124929/e433f289-41e3-40b0-8682-1c949fe2f27d)

Notification Button Before
![_before](https://github.com/Mehak261124/jupyterlab/assets/145124929/8534b9d0-63d5-4534-9ee1-abdf2d321534)

Notification Button After
![_after](https://github.com/Mehak261124/jupyterlab/assets/145124929/4082b306-06e4-4a14-ae2e-228ba0a94e71)

2024-06-04 07:44 UTC, fcollonval commented on packages/ui-components/src/icon/labicon.tsx
> +          slot,
You should probably remove this attribute as it is already mentioned at line 460

```suggestion
```

2024-06-04 07:56 UTC, fcollonval commented on packages/debugger/src/panels/kernelSources/filter.tsx
Those changes should not be part of this PR.

2024-06-04 07:56 UTC, fcollonval commented on packages/notebook/src/widget.ts
Those changes should not be part of this PR.

2024-06-04 08:01 UTC, fcollonval requested changes

2024-06-04 08:04 UTC, fcollonval commented on packages/ui-components-extension/package.json
Those changes should not be part of this PR.

2024-06-04 09:03 UTC, fcollonval requested changes
Hey @Mehak261124 

I had a look at the PR. Some preliminary comments about git. You should not develop on the `main` branch of your fork. Please read that [tutorial](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow) about the forking workflow using feature branches.
it will avoid unwanted changes to slip into your PRs and will allow you to develop features in parallel.

Regarding the PR content, I would recommend making one more changes to have the `Button` in `@jupyterlab/ui-components` wrapping a `Button` from `@jupyter/react-components`:

```ts
// in packages/ui-components/src/components/button.tsx

import { Button as ToolkitButton } from '@jupyter/react-components'

// ...

export function Button(props: IButtonProps): JSX.Element {
   // ...
   return (<ToolkitButton ...>
     ...
   </ToolkitButton>);
}
```

2024-06-04 14:43 UTC, closed without merging

2024-06-04 16:03 UTC, Mehak261124 commented
Hey @fcollonval I closed this pull request (PR) and subsequently submitted a new PR on the basis of above tutorial.

2024-06-04 19:51 UTC, ericsnekbytes commented
@Mehak261124 Can you link the new one here?

2024-06-07 09:53 UTC, Mehak261124 commented
Hey @fcollonval @ericsnekbytes @krassowski this is the link of my new pull request (https://github.com/jupyterlab/jupyterlab/pull/16438)