Add typings to the inline completer example
jupyterlab/jupyterlab pull request #16421
Opened 2024-06-03 17:55 UTC by jtpio

## References

Add typings to the inline completer example: https://jupyterlab.readthedocs.io/en/latest/extension/extension_points.html#inline-completer

To make easier to copy and paste the example, and have the extension build directly.

## Code changes

Documentation update.

## User-facing changes

None

## Backwards-incompatible changes

None

2024-06-03 18:43 UTC, krassowski submitted a review, later dismissed
Thank you @jtpio!

2024-06-03 18:47 UTC, krassowski requested changes
Sorry, I was too quick at first pass. I think you wanted to make the changes in `Inline Completer` section but you made them in `Code Completer` section. I added suggestions on the modified lines of code but GitHub UI does not allow me to add suggestions lower down on the `Inline Completer` section

2024-06-03 18:47 UTC, krassowski commented on docs/source/extension/extension_points.rst
> +      IInlineCompletionProvider
```suggestion
      ICompletionProviderManager,
      ICompletionContext,
      ICompletionProvider
```

2024-06-03 18:47 UTC, krassowski commented on docs/source/extension/extension_points.rst
> +      async isApplicable(context: IInlineCompletionContext) {
```suggestion
      async isApplicable(context: ICompletionContext) {
```

2024-06-03 18:47 UTC, krassowski commented on docs/source/extension/extension_points.rst
> +        context: IInlineCompletionContext
```suggestion
        request: CompletionHandler.IRequest,
        context: ICompletionContext
```

2024-06-03 18:49 UTC, jtpio commented
Ah yes good catch, it was one section below!

Fixing that now.

2024-06-04 07:55 UTC, jtpio commented
Thanks for the review!

2024-06-04 07:56 UTC, merged

2024-06-04 07:56 UTC, jtpio commented
@meeseeksdev please backport to 4.2.x