[GSoC 2024] Use toolkit for the settings editor
jupyterlab/jupyterlab pull request #16536
Opened 2024-06-30 13:05 UTC by Mehak261124

**Issue:**
Inconsistencies have arisen in the user interface across various JupyterLab extensions, including the Table of Content, Debugger Variables, and Running tabs.

**Background:**
This update aims to introduce a variety of user interface components in the settings editor to enhance functionality and user interaction across JupyterLab.

**Description of New Features in Settings Editor:**
The settings editor will now include the following toolkit components to cater to different user needs:

**Input:** This component allows users to enter text or numeric values. It can be used to capture information such as names, email addresses, phone numbers, and more.
**Option:** This component presents users with a set of predefined choices. It can be used to select preferences, enable or disable features, or make other binary decisions.
**Button:** This component triggers an action when clicked. It can be used to save changes, submit forms, navigate to different pages, or perform other tasks.
**Select:** This component allows users to choose from a list of options. It can be used to select items from a menu, filter content, or perform other selection-based tasks.
**Search:** This component provides a search bar where users can enter keywords to find specific content or information. It can be used to search through a list of items, a database, or other resources.

**Goals:**
These components are designed to be flexible and customizable, allowing developers to easily integrate them into their applications and create intuitive and user-friendly interfaces. This enhancement aims to improve the consistency and accessibility of JupyterLab's user interface, making it more streamlined and efficient for all users.

2024-07-09 08:13 UTC, fcollonval commented on packages/ui-components/src/components/form.tsx
> +    // @ts-expect-error I know
This one can be dropped:

```suggestion
```

2024-07-09 08:14 UTC, fcollonval commented on packages/ui-components/src/components/form.tsx
> +import { WidgetProps } from '@rjsf/utils';
You need to add those imports:

```suggestion
import { 
  ariaDescribedByIds,
  schemaRequiresTrueValue,
  FormContextType,
  RJSFSchema,
  StrictRJSFSchema,
  WidgetProps
} from '@rjsf/utils';
```

2024-07-09 08:18 UTC, fcollonval commented
It will be great to create custom widgets for:

- [ ] CheckboxesWidget
- [x] CheckboxWidget
- [ ] RadioWidget
- [ ] SelectWidget
- [ ] TextareaWidget
- [ ] TextWidget

2024-07-10 15:39 UTC, fcollonval reviewed
It looks like a good start.

Here are some suggestions

2024-07-10 15:39 UTC, fcollonval commented on packages/ui-components/src/components/form.tsx
> +  };
The callback `OnOptionSelect` does not exist on the toolkit.

You gonna have to use `onChange(event) {}`. And to determine the `newValue`, you should be able to do something like

```ts
const _onChange = (event) => {
  const newValue = multiple ? (event.target as any).selectedOptions : (event.target as any).value;
}
```

2024-07-10 15:39 UTC, fcollonval commented on packages/ui-components/src/components/form.tsx
> +      <Select
For this case I think you can use the `label` element directly and move the other attribute on `Select`

```suggestion
    <label>
      {labelValue(label, hideLabel)}
      <Select
        aria-invalid={rawErrors.length > 0}
        required={required}
```

2024-07-11 13:33 UTC, fcollonval commented on packages/ui-components/src/components/form.tsx
>          className='form-control'
In our case, the attribute for multiple selection is `multiple`. And let's not set a class name for now.

```suggestion
        multiple={multiple}
```

2024-07-11 13:33 UTC, fcollonval commented
@Mehak261124 could you rebase this branch on the main branch (or merge main branch into it)?

2024-07-20 13:57 UTC, fcollonval requested changes
Thanks @Mehak261124 here are some comments about the PR

2024-07-20 13:57 UTC, fcollonval commented on docker/Dockerfile
> +  usermod -o "-u ${NEW_MAMBA_USER_ID}" "${MAMBA_USER}"; \
@Mehak261124 could you either explain or remove the changes in the docker configuration?

2024-07-20 13:57 UTC, fcollonval commented on packages/ui-components/src/components/widgets/checkboxWidget.tsx
> +// import React from 'react';
Could you remove the commented code?

2024-07-20 13:57 UTC, fcollonval commented on packages/ui-components/src/components/widgets/checkboxesWidget.tsx
> +          </label>
For consistency with the checkbox widget, I would not warp the checkbox within a label but set the label as the child of `Checkbox`:

```suggestion
          <Checkbox
              id={optionId(id, index)}
              key={optionId(id, index)}
              name={id}
              checked={checked}
              disabled={disabled || itemDisabled || readonly}
              // autoFocus={autofocus && index === 0}
              onChange={_onChange(index)}
              onBlur={_onBlur}
              onFocus={_onFocus}
              aria-describedby={ariaDescribedByIds<T>(id)}
          >
            {option.label}
          </Checkbox>
```

2024-07-20 14:10 UTC, fcollonval commented
As I was fearing the CI is having the same issue as me locally. Could you rebuild your docker image? I think this is the reason you are not seeing that issue locally.

The common issue is:

```
  ../ui-components/src/components/widgets/textWidget.tsx(97,9): error TS2322: Type '((event: ChangeEvent<HTMLInputElement>) => void) | undefined' is not assignable to type '((event: CustomEvent<any>) => void) | undefined'.
    Type '(event: ChangeEvent<HTMLInputElement>) => void' is not assignable to type '(event: CustomEvent<any>) => void'.
      Types of parameters 'event' and 'event' are incompatible.
        Type 'CustomEvent<any>' is not assignable to type 'ChangeEvent<HTMLInputElement>'.
  ../ui-components/src/components/widgets/textareaWidget.tsx(69,7): error TS2322: Type '({ target: { value } }: ChangeEvent<HTMLTextAreaElement>) => void' is not assignable to type '(event: CustomEvent<any>) => void'.
    Types of parameters '__0' and 'event' are incompatible.
      Type 'CustomEvent<any>' is missing the following properties from type 'ChangeEvent<HTMLTextAreaElement>': nativeEvent, isDefaultPrevented, isPropagationStopped, persist
```

> It applies to other widgets than the `textwidget`.

2024-07-31 13:43 UTC, fcollonval requested changes
Thanks @Mehak261124 

It looks great. One issue I saw is with the label appearing twice for the `SelectWidget`. I have a suggestion to fix that.

Then to make the setting editor more homogeneous, there are two other points we could tackle:

- Use the toolkit button (`import {Button} from '@jupyter/react-components';`) for the editor buttons:

https://github.com/jupyterlab/jupyterlab/blob/015b490c668f921a5c600d3c9824460063cd2ab4/packages/ui-components/src/components/form.tsx#L159-L165

should become

```ts
 <Button 
   className="jp-ArrayOperationsButton" 
   onClick={props.item.onReorderClick(props.item.index, moveTo)} 
   disabled={disabled()} 
 > 
   {buttonContent} 
 </Button> 
```

https://github.com/jupyterlab/jupyterlab/blob/015b490c668f921a5c600d3c9824460063cd2ab4/packages/ui-components/src/components/form.tsx#L193-L198

should become

```ts
 <Button 
   appearance="error"
   className="jp-ArrayOperationsButton" 
   onClick={props.item.onDropIndexClick(props.item.index)} 
 > 
   {buttonContent} 
 </Button> 
```

https://github.com/jupyterlab/jupyterlab/blob/015b490c668f921a5c600d3c9824460063cd2ab4/packages/ui-components/src/components/form.tsx#L222-L227

should become

```ts
 <button 
   className="jp-ArrayOperationsButton" 
   onClick={props.onAddClick} 
 > 
   {buttonContent} 
 </Button> 
```

- Use the `NumberField` component instead of `input` for the following component:

https://github.com/jupyterlab/jupyterlab/blob/2458fd1466287c2a4f9951937a00319ac35d9f34/packages/completer-extension/src/renderer.tsx#L64-L71

should become

```ts
 <NumberField
   className="form-control" 
   value={settingValue[key]} 
   onChange={e => { 
     onSettingChange(key, e); 
   }} 
 /> 
```

2024-07-31 13:43 UTC, fcollonval commented on packages/ui-components/src/components/widgets/selectWidget.tsx
> +      {labelValue(label, hideLabel)}
Dropping the label should solve the issue with the label appearing twice

```suggestion
```

2024-07-31 13:43 UTC, fcollonval commented on packages/ui-components/src/components/widgets/selectWidget.tsx
> +    </label>
```suggestion
```

2024-08-01 13:45 UTC, fcollonval reviewed
Thanks @Mehak261124 for the latest changes.

Could you
- run `jlpm run integrity` and commit the changes to fix the integrity tests?
- the metadataform JS unit test failing needs the following correction instead of  

https://github.com/jupyterlab/jupyterlab/blob/2458fd1466287c2a4f9951937a00319ac35d9f34/packages/metadataform/test/metadataFormWidget.spec.ts#L152-L156

set

```ts
 expect( 
   node 
     .getElementsByClassName('jp-inputFieldWrapper')[0] 
     .children[0].tagName
 ).toBe('JP-NUMBER-FIELD'); 
```

For the integration tests, the setting editor itself is not tested. But I forgot that the metadataform (one of the right sidebar) is also using the component and it is extensively tested - hence the issue. Do you want me to have a look at the failures or do you want to give a stab at them?

2025-02-04 17:14 UTC, Mehak261124 commented
Hey @fcollonval  
I'm closing this PR as it became too messy to manage. Instead, I’ve opened a new PR with the same changes: https://github.com/jupyterlab/jupyterlab/pull/17259 . You can refer to this one moving forward.

2025-02-04 17:15 UTC, closed without merging