Use locale name instead of display/native name to toggle languag
jupyterlab/jupyterlab pull request #16710
Opened 2024-08-22 19:16 UTC by maitreya2954

## References

Fixes #16620 

## Code changes

The fix uses locale name to decide which language to toggle instead of looking for menu string being identical for the language name in the current language and the target language.

## User-facing changes
NA

## Backwards-incompatible changes

NA

2024-08-23 00:24 UTC, JasonWeill approved these changes
Change looks good. Thank you!

2024-08-23 06:19 UTC, krassowski commented
The visual regressions failures appear relevant:

    [jupyterlab] › test/jupyterlab/menus.test.ts:40:7 › General Tests › Open language menu ─────────

2024-08-23 06:30 UTC, krassowski requested changes
Based on the snapshot changes I am not convinced that this change works as expected. I would have expected English to remain selected as the default language, but it is not the case. This is seen in a number of snapshots, including:


| Before | After |
|---|---|
| ![language-settings-expected](https://github.com/user-attachments/assets/91437d24-57b1-4b4e-9194-450ad446545c) | ![language-settings-actual](https://github.com/user-attachments/assets/d46aafd3-9a25-49d8-97ef-8f4ea7b40c6a) |


| Before | After |
|---|---|
| ![command-palette-expected](https://github.com/user-attachments/assets/dbb918c7-ddd3-49f9-85b3-ef698bdbc029) | ![command-palette-actual](https://github.com/user-attachments/assets/e0210572-92d2-4ef6-aed5-0881557f6f5a) |

2024-08-23 14:32 UTC, JasonWeill commented
Looks like the test failures are directly related to this change; it causes an "English - English" (not "English") menu option to appear when the default language is English. @krassowski is this something that needs to be fixed, or should we update the screen shots to set a new expectation?

2024-08-23 15:24 UTC, maitreya2954 commented
I'm new to contributing to jupyter lab so please correct me if I am wrong. This failure seems to happen when the `currentLocale` is default [here](https://github.com/jupyterlab/jupyterlab/pull/16710/files#diff-dc8849d9665d7cc134f7e2c7b117906e202dbdddb957ab3ac4c041ebeb09d2caR136) which is then being considered as `en-US`. But, the locale from translations api for English is `en` which doesn't toggle English causing "English - English". 

@krassowski @JasonWeill I can think of two ways to go about it

1.  Consider `en` as default language instead of `en-US`. (Might break if translations api does actually send `en-US`)
2. Consider just language identifier of the code. So, `en-US` and `en` will both be considered `en`.  

What do you guys think?

2024-08-23 16:49 UTC, JasonWeill commented
I don't think that using only the language identifier would be suitable; there's a significant political meaning associated with zh-CN, which uses simplified Chinese characters, and zh-TW, which uses traditional characters, for example. Would it be OK to render "X - X" as just "X" if the source and target language's word is identical?

2024-08-23 17:28 UTC, krassowski commented
> it causes an "English - English" (not "English") menu option to appear when the default language is English. @krassowski is this something that needs to be fixed, or should we update the screen shots to set a new expectation?

This needs to be fixed because it is incorrect. The English language is active and it should not pollute the command pallete options/mislead user in the menu.

2024-08-23 17:30 UTC, krassowski commented
> Would it be OK to render "X - X" as just "X" if the source and target language's word is identical?

I think we should do this but it is tangential to the underlying implementation. I think there is a separate issue for it.

2024-08-23 17:30 UTC, krassowski commented
> I don't think that using only the language identifier would be suitable; there's a significant political meaning associated with zh-CN, which uses simplified Chinese characters, and zh-TW, which uses traditional characters

Good point, agreed. I would say let's try (1).

2024-08-23 18:14 UTC, maitreya2954 commented
@krassowski Will this [commit](https://github.com/jupyterlab/jupyterlab/pull/16710/commits/f043d9c2bc8ffaadd2b234e0f4b7c6d0e0384297) do?

2024-08-23 22:45 UTC, krassowski approved these changes
It seems it does :) Thank you @maitreya2954!

2024-08-24 07:28 UTC, merged

2024-08-24 07:28 UTC, krassowski commented
@meeseeksdev please backport to 4.2.x