suffix encoding added for header ids
jupyterlab/jupyterlab pull request #16845
Opened 2024-10-08 22:54 UTC by onursercanyilmaz

## References
Fixes #1932  #16795  #12402

## Code changes

Changes in renderers.tsx, as shown below.

```
  export function headerAnchors(node: HTMLElement): void {
    const headerNames = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'];
    for (const headerType of headerNames) {
      const headers = node.getElementsByTagName(headerType);
      for (let i = 0; i < headers.length; i++) {
        const header = headers[i];
        const parentElement = header.closest(
          '.lm-Widget.jp-Cell.jp-MarkdownCell.jp-Notebook-cell.jp-mod-rendered'
        );
        const parentIndex =
          parentElement?.getAttribute('data-windowed-list-index') ?? '0';
        header.id = renderMarkdown.createHeaderId(header, i, parentIndex);
        const anchor = document.createElement('a');
        anchor.target = '_self';
        anchor.textContent = '¶';
        anchor.href = '#' + header.id;
        anchor.classList.add('jp-InternalAnchorLink');
        header.appendChild(anchor);
      }
    }
  }
  
   export function createHeaderId(header: Element, index: number, parentIndex: string): string {
    return (`${header.textContent} ${index} ${parentIndex}` ?? '').replace(/ /g, '-');
  }
```

If a cell includes more than 1 header it adds 'i' (index) to id and after that adds the parent div's index info as header-{innerIndex}-{parentIndex}. Issue is about parentIndex problem but there was another problem on inner headers that solved too.

![image](https://github.com/user-attachments/assets/d6a745ba-5760-4f1c-9699-5a2e5a94e3ce)

But still there was an issue that for example - if user adds #Part 1 as h1 and ##Part 1 as h2 - it creates same id.
So i added headerType parameter too

```
  export function createHeaderId(
    header: Element,
    index: number,
    parentIndex: string,
    headerType: string,
  ): string {
    return (`${header.textContent} ${index} ${parentIndex} ${headerType}` ?? '').replace(
      / /g,
      '-'
    );
  }
  
   export function headerAnchors(node: HTMLElement): void {
    const headerNames = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'];
    for (const headerType of headerNames) {
      const headers = node.getElementsByTagName(headerType);
      for (let i = 0; i < headers.length; i++) {
        const header = headers[i];
        const parentElement = header.closest(
          '.lm-Widget.jp-Cell.jp-MarkdownCell.jp-Notebook-cell.jp-mod-rendered'
        );
        const parentIndex =
          parentElement?.getAttribute('data-windowed-list-index') ?? '0';
        header.id = renderMarkdown.createHeaderId(header, i, parentIndex, headerType);
        const anchor = document.createElement('a');
        anchor.target = '_self';
        anchor.textContent = '¶';
        anchor.href = '#' + header.id;
        anchor.classList.add('jp-InternalAnchorLink');
        header.appendChild(anchor);
      }
    }
  }
```
  
![image](https://github.com/user-attachments/assets/e6c77489-89bc-4c1a-802a-b8476e58beaf)
![image](https://github.com/user-attachments/assets/b08237f9-9963-4520-b11b-29e14f708924)

But i think it seems not good. So I decided to encode suffix part
```
 function encodeSuffix(
    index: number,
    parentIndex: string,
    headerType: string
  ): string {
    const suffix = `${index} ${parentIndex} ${headerType}`;

    // Use TextEncoder to convert the string to a Uint8Array
    const encoder = new TextEncoder();
    const data = encoder.encode(suffix);

    // Convert to Base64
    let binaryString = '';
    for (let i = 0; i < data.length; i++) {
      binaryString += String.fromCharCode(data[i]);
    }

    return btoa(binaryString);
  }

  export function createHeaderId(
    header: Element,
    index: number,
    parentIndex: string,
    headerType: string
  ): string {
    const suffix = encodeSuffix(index, parentIndex, headerType);
    return (`${header.textContent} ${suffix}` ?? '').replace(/ /g, '-');
  }

```

![image](https://github.com/user-attachments/assets/d532f534-ab9e-4e64-93cf-ede21d078eec)

- But furthermore if user types any emoji or non-english chars in headers, it will affect the id and the url
So we can add headerText as parameter in encodeSuffix function
```

  function encodeSuffix(
    headerText: string | null,
    index: number,
    parentIndex: string,
    headerType: string
  ): string {
    const suffix = `${headerText} ${index} ${parentIndex} ${headerType}`;

    // Use TextEncoder to convert the string to a Uint8Array
    const encoder = new TextEncoder();
    const data = encoder.encode(suffix);

    // Convert to Base64
    let binaryString = '';
    for (let i = 0; i < data.length; i++) {
      binaryString += String.fromCharCode(data[i]);
    }

    return btoa(binaryString);
  }

  export function createHeaderId(
    header: Element,
    index: number,
    parentIndex: string,
    headerType: string
  ): string {
    const suffix = encodeSuffix(
      header.textContent,
      index,
      parentIndex,
      headerType
    );
    return (`${suffix}` ?? '').replace(/ /g, '-');
  }
}

```

## User-facing changes
- Users will now see the newly generated id in the URL when they click on header items, as the id attributes are assigned to the <a> tags as href values.

![image](https://github.com/user-attachments/assets/b19288f2-28dd-4a8b-a11e-8066999ebe16)

![image](https://github.com/user-attachments/assets/59493578-bbbe-479f-a493-90fb9d3c8233)

![image](https://github.com/user-attachments/assets/a7646a3a-fdcc-4959-9d10-ed319c92e93a)

- [x] Linking to headers in the same notebook
- [x] Multiple headers have the same text, ids conflict solved by adding parent div index info
- [x] encodeSuffix solves non-english char problem
- [x] Adding headers in same or different cells with different id information
- [x] No any non-english char in id or link -> #12402
- [x] Not created a uuid because it will create different id info for each render. But giving static info to convert it base64 is better to linking headers 

Here’s the detailed explanation:

### **Cause:**
In JupyterLab, when assigning IDs to markdown headers, each cell (node) operates in isolation, meaning only the headers within that cell are considered. Since there is no global ID system, the following issues arise:

1. When the same or different cells use the same header text, the same IDs are repeated. For example:
    - If a **h1** tag is created in Cell 1 with the text "Header," its ID will be `Header`.
    - If the same "Header" is created in Cell 2, this header will also be assigned the ID `Header`.

2. Additionally, when emojis or special characters are used in headers, they are included in the IDs. For example, if a header text is "🚀 Start," it will be assigned the ID `🚀-Start`. This situation reduces the readability and consistency of the IDs.

### **Development:**
Using a **counter** to create unique IDs based on header text might seem logical, but since each cell operates independently, this method fails. Specifically:

- The **node** resets to zero in each cell. For example:
    - If there are two **h1** headers in Cell 1, they might be assigned IDs `Header` and `Header-1`.
    - However, if the same headers are used in Cell 2, the count starts again from zero, resulting in the same IDs: `Header` and `Header-1`.

- In this case, the **counter** method can only apply within that cell, meaning it cannot ensure global uniqueness across cells. As cells are isolated, the **counter** solution proves inadequate for establishing unique IDs.

**Example:**
Cell 1:
```markdown
# Header
# Header
```
IDs: `Header`, `Header-1`

Cell 2:
```markdown
# Header
# Header
```
IDs: again `Header`, `Header-1`, leading to conflicts.

### **Result:**
To resolve this issue, I got a unique **parentId** (or parentIndex) for each cell to ensure the headers have unique IDs. With this method:

1. Each header text had its cell's **parentId** value appended (Each cell's div tag has a data-windowed-list-index attribute value = parentIndex), allowing for differentiation even if  [...]

2024-10-09 10:32 UTC, HaudinFlorence commented
@onursercanyilmaz Thanks for the details explanation you gave on your previous PR and reported here.
I just tested a simple notebook and console. log the information collected to build the suffix before encoding it. The information are correct when I start a new jupyterlab and open the notebook. The only issue I observed is when modifying the notebook by changing headers, saving it:, the `ParentIndex` and the `index` seem then to be zero in any case. It seems that jupyterlab needs to be refresh to get back the correct result. Maybe this is normal and expected as a behavior. But that the reason why I was not able to get the correct `ParentIndex` and `index` previously.

2024-10-09 16:44 UTC, HaudinFlorence commented
There is also this case that could (very rarely) happen: opening 2 notebooks with similar contents or the same headings contents for the first cell for example. In that situation it is possible to have in the DOM 2 elements having the same id as shown on the following example:
![Screenshot from 2024-10-09 18-37-10](https://github.com/user-attachments/assets/bb90edb4-88dd-487f-aff1-83d900a1b3db)
![Screenshot from 2024-10-09 18-37-18](https://github.com/user-attachments/assets/1b6cec49-baea-4284-9cf9-ab377d3a3d80)
This should be prevented if possible with introducing an identifier related to the notebook.

2024-10-10 09:43 UTC, krassowski requested changes
The problem with changing the format of the anchors is that users have embedded them as cross-links in their notebooks, so any change is breaking in a very bad way - basically links between existing notebooks will stop working. While I do like the approach of using based64 encoding, I believe that we should find a way to make this change backward compatible, for example by keeping the old header ID format AND add the new one on top of that (which would require rendering two HTML elements for each heading).

Regarding the issues that @HaudinFlorence brought up: when two notebooks are open side-by-side JupyterLab should be able to resolve the ambiguity because the notebook name is also embedded in the URL. There is dedicated routing code dealing with hash IDs - I don't think this should be addressed in this PR. I also don't think we should embed the notebook name in the ID as that can change frequently outside of Jupyter.

2026-05-14 15:38 UTC, krassowski commented
Closing since this was in draft in for over 1.5 year and as of now uses a backward-incompatible approach. Thank you for exploring this!

2026-05-14 15:38 UTC, closed without merging