MathJax: change font from STIX-Web to TeX
jupyterlab/jupyterlab pull request #9907
Opened 2021-03-06 14:58 UTC by mgeier

## References

#5192

https://github.com/jupyter/notebook/pull/5998

## Code changes

Just changing `STIX-Web` to `TeX`.

## User-facing changes

Much nicer font for equations.

## Backwards-incompatible changes

none

2021-03-22 16:43 UTC, jasongrout commented
Checking the history, it looks like the stix fonts were introduced in https://github.com/jupyterlab/jupyterlab/pull/748 (0afcbee9e3ba830be23281790e1afe29c4d1d78f), fixing https://github.com/jupyterlab/jupyterlab/issues/590

2021-03-22 16:57 UTC, jasongrout commented
When I test this PR, mathjax rendering looks bad with this error in the js console:

```
GEThttp://localhost:8890/static/nbclassic/components/MathJax/jax/output/HTML-CSS/fonts/TeX/fontdata.js?V=2.7.9
[HTTP/1.1 404 Not Found 3ms]

Loading failed for the <script> with source “http://localhost:8890/static/nbclassic/components/MathJax/jax/output/HTML-CSS/fonts/TeX/fontdata.js?V=2.7.9”.
```
<img width="127" alt="Screen Shot 2021-03-22 at 9 55 48 AM" src="https://user-images.githubusercontent.com/192614/112027922-e85d1600-8af4-11eb-92de-7ddeab237225.png">

It looks like the tex fonts are not shipped with the notebook?

2021-03-22 17:07 UTC, jasongrout commented
Checking into the `notebook` package I have installed, in `lib/python3.9/site-packages/notebook/static/components/MathJax/fonts/`, it does indeed look like only the stix-web fonts are installed by default.

In order to move forward here, it looks like we need to decide:

A. Do we ship mathjax with jlab (or depend on https://pypi.org/project/jupyter-server-mathjax/?), and decide about which font to use
B. Change notebook to ship tex fonts?
C. Perhaps just wait to switch to the mathjax 3 plugin, which bundles tex fonts since tex fonts are the only fonts available for mathjax 3.

2021-03-22 17:07 UTC, jasongrout requested changes
Checking into the `notebook` package I have installed, in `lib/python3.9/site-packages/notebook/static/components/MathJax/fonts/`, it does indeed look like only the stix-web fonts are installed by default.

In order to move forward here, it looks like we need to decide:

A. Do we ship mathjax with jlab (or depend on https://pypi.org/project/jupyter-server-mathjax/?), and decide about which font to use
B. Change notebook to ship tex fonts?
C. Perhaps just wait to switch to the mathjax 3 plugin, which bundles tex fonts since tex fonts are the only fonts available for mathjax 3.

2021-04-06 08:46 UTC, mgeier commented
@jasongrout Regarding your point B, do you mean something like https://github.com/jupyter/notebook/issues/2536?

2021-05-28 16:17 UTC, goanpeca commented
I think this needs a reply from @jasongrout :)

2021-06-02 11:02 UTC, jasongrout commented
> @jasongrout Regarding your point B, do you mean something like [jupyter/notebook#2536](https://github.com/jupyter/notebook/issues/2536)?

Yes.

I'll note from https://github.com/jupyter/notebook/pull/5998#issuecomment-826090865:

> It looks like in the meantime the situation has magically improved on its own (at the MathJax side I guess?).
> Previously, bold symbols -- especially when decorated with \boldsymbol{\hat{...}} or something -- looked hideous. But now that has become much better.
> The remaining differences are quite subtle.

2022-08-19 00:24 UTC, jweill-aws commented
There hasn't been any activity on this pull request in over a year. As part of an effort to clean up this repository's pull requests, I'm closing this request. If you would still like to merge this code in, please reopen the request and resolve any outstanding merge conflicts. All of the code and comments will remain in place. Thank you for being part of the JupyterLab community!

2022-08-19 00:24 UTC, closed without merging

2022-12-04 18:46 UTC, mgeier commented
I think this becomes obsolete once JupyterLab switches to MathJax 3 (#7218), which should be done rather sooner than later! Please!